# data structures - python
* to store or get multiple data or values in built in structures

## 4 types of data structures:
1. list
2. set
3. tuple
4. libraries

### list

* accepts duplicate values
* single dimension
* inside square bracket
* heterogenous data accepted - string, int, float
* indexing for the position automatically done  - strat with 0 from lft - start with -1 from right
* slicing can be done 0:2 - fetches values in 0,1 poistion always excluding the last positin number(here 2) - so values in 0 and 1 are displayed
* mutable - values in any position can be changed in future (marks[2] = 23) this will update the values

In [10]:
stu_marks = [54,76,87,98,90]
stu_marks

[54, 76, 87, 98, 90]

In [14]:
type(stu_marks) ##returns the type of data structures it is stored

list

In [31]:
stu_marks[-4:-1] ##fetch particular index value & slicing

[76, 87, 98]

In [32]:
stu_marks[3] = 100

In [33]:
stu_marks

[54, 76, 87, 100, 90]

### set

* accepts only unique values, duplicates truncated automatically
* single dimension
* inside curly braces
* heterogenous data accepted - string, int, float
* indexing and slicing is not possible
* mutable - values can be added or removed thru functions()

In [34]:
empty_set = set() # create an empty set

In [35]:
type(empty_set)

set

In [42]:
items_to_buy = {"apple","grape","guava","pomo","melon",45,2.3,"guava"}

In [43]:
type(items_to_buy)"apple","grape","guava","pomo","melon",45,2.3,"guava"

set

In [45]:
items_to_buy.add("banana")

In [47]:
items_to_buy

{2.3, 45, 'apple', 'banana', 'grape', 'guava', 'melon', 'pomo'}

## tuple

* duplicates allowed
* single dimension
* inside paranthesis
* heterogenous data accepted - string, int, float
* indexing and slicing is possible
* 
* immutable - values cannot be assigned at a later stage not thru indexing nor a function

In [49]:
new_tuple = ()

In [50]:
type(new_tuple)

tuple

In [51]:
items = ("apple","grape","guava","pomo","melon",45,2.3,"guava")

In [52]:
items

('apple', 'grape', 'guava', 'pomo', 'melon', 45, 2.3, 'guava')

In [54]:
items[0:4]

('apple', 'grape', 'guava', 'pomo')

In [55]:
items[2] = "cane"

TypeError: 'tuple' object does not support item assignment

In [59]:
items.index("apple")

0

## dictionary - key and value
* its a key:value pair
* two dimensional values
* inside curly braces with key:value 
* heterogenous data accepted - string, int, float
* keys cannot be duplicate, values can be repeated for diff keys
* if duplicate keys given, latest value given to the keys are updated and previous values are erased
* indexing and slicing cannot be done
* but the keys and values are fetched seperately thru functions()

In [60]:
empty_dict = {}

In [61]:
type(empty_dict)

dict

In [113]:
empty_dict = {'ram':[34,34,21,54],'ravi':[32,54,65,76],'priya':[43,65,76,87],'ravi':[33,43,76,87]}

In [114]:
type(empty_dict)

dict

In [115]:
empty_dict

{'ram': [34, 34, 21, 54], 'ravi': [33, 43, 76, 87], 'priya': [43, 65, 76, 87]}

In [101]:
empty_dict[0:2] ## slicing cant be done

KeyError: slice(0, 2, None)

In [80]:
empty_dict.update([ravi, ] 33)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2798796450.py, line 1)

In [116]:
import pandas as pd
pd.DataFrame(empty_dict,index=None,columns=None,dtype=None,copy=None)

   ram  ravi  priya
0   34    33     43
1   34    43     65
2   21    76     76
3   54    87     87

In [119]:
student_marks = {'names':["Riya","Priya","raju","rambo"],
                 'math':[34,34,21,54],
                 'science':[32,54,65,76],
                 'ela':[43,65,76,87],
                 'comp':[33,43,76,87]}

In [120]:
import pandas as pd
pd.DataFrame(student_marks,index=None,columns=None,dtype=None,copy=None)

   names  math  science  ela  comp
0   Riya    34       32   43    33
1  Priya    34       54   65    43
2   raju    21       65   76    76
3  rambo    54       76   87    87