# 1.Import Necessary Libraries

In [1]:
import pandas as pd

# 2. Load Data

## 2.a. SKU Table

In [106]:
SKU_Table = pd.read_xml("SKU_Table.xml")

In [228]:
SKU_Table_cleaned.shape

(1546, 2)

In [108]:
SKU_Table["Sku"] = SKU_Table["Sku"].astype("string").str.strip()
SKU_Table["PN"] = SKU_Table["PN"].astype("string").str.strip()
SKU_Table = SKU_Table.rename(columns={"PN" : "Product Number", "Sku" : "SKU"})

In [224]:
print("\nData Types::::::::\n", SKU_Table.dtypes)
print("\n ***************************************************** \n")
print("\nDescription ::::::::::\n",SKU_Table_cleaned.describe(include='all'))
print("\n ***************************************************** \n")
print("\nTotal Null values::::::::\n",SKU_Table.isnull().sum())
print("\n ***************************************************** \n")
print("\n Duplicated SKU count:::::::\n",SKU_Table['SKU'].duplicated().sum())
print("\n Duplicated Product Number Count:::::::::::\n",SKU_Table['Product Number'].duplicated().sum())

Data Types::::::::
 Product Number    string
SKU               string
dtype: object

 *****************************************************


Description ::::::::::
        Product Number      SKU
count            1546     1546
unique           1546     1546
top           Pib01a1  0X749QB
freq                1        1

 *****************************************************


Total Null values::::::::
 Product Number    0
SKU               0
dtype: int64

 *****************************************************


 Duplicated SKU count:::::::
 0

 Duplicated Product Number Count:::::::::::
 0

In [223]:
SKU_duplicates = SKU_Table[SKU_Table["SKU"].duplicated(keep=False)]
SKU_duplicates
#### NEED TO VERIFY OTHER TABLES ALSO BEFORE WE REMOVE DUPLICATES

Empty DataFrame
Columns: [Product Number, SKU]
Index: []

In [222]:
SKU_Table_cleaned = SKU_Table[
    ~SKU_Table['SKU'].isin(SKU_List)
].copy()

In [221]:
# Remove duplicate SKUs and keep the first occurrence
SKU_Table = SKU_Table.drop_duplicates(subset=['SKU'], keep='first')

# Reset the index
SKU_Table = SKU_Table.reset_index(drop=True)

# Check the result
print(SKU_Table.shape)
print(SKU_Table['SKU'].duplicated().sum())

(1594, 2)
0

In [226]:
SKU_Table_cleaned.to_excel(
    r"C:\Data Science\MAP Project\Cleaned files\SKU_Table_cleaned.xlsx",
    index=False
)

## 2.b. Product Line Table

In [116]:
Product_Line_Table = pd.read_json("Product Line Table.json", lines=True)

In [131]:
Product_Line_Table_cleaned.head()

       SKU       Product Line Sub Category
0  0X749QB   DELL0X_PC_Laptop       Laptop
1  75X62BB  DELL75_PC_Monitor      Monitor
2   DF627B     DELLDF_SUP_TON        Toner
3   4ZB96A         HP4Z_PH_LJ    Laser Jet
4  0R0N0QB   DELL0R_PC_Laptop       Laptop

In [118]:
Product_Line_Table["sku"] = Product_Line_Table["sku"].astype("string").str.strip()
Product_Line_Table["PL"] = Product_Line_Table["PL"].astype("string").str.strip()
Product_Line_Table = Product_Line_Table.rename(columns={ "sku" : "SKU","PL" : "Product Line"})

In [236]:
print("\nData Types::::::::\n", Product_Line_Table.dtypes)
print("\n ***************************************************** \n")
print("\nDescription ::::::::::\n",Product_Line_Table_cleaned.describe(include='all'))
print("\n ***************************************************** \n")
print("\nTotal Null values::::::::\n",Product_Line_Table.isnull().sum())
print("\n ***************************************************** \n")
print("\n Duplicated SKU count:::::::\n",Product_Line_Table['SKU'].duplicated().sum())

Data Types::::::::
 SKU             string
Product Line    string
Sub Category    string
dtype: object

 *****************************************************


Description ::::::::::
             SKU    Product Line Sub Category
count      1546            1546         1546
unique     1546             416            7
top     0X749QB  DELLDG_SUP_TON          Ink
freq          1              62          426

 *****************************************************


Total Null values::::::::
 SKU             0
Product Line    0
Sub Category    0
dtype: int64

 *****************************************************


 Duplicated SKU count:::::::
 0

In [231]:
Product_Line_Table_duplicates = Product_Line_Table[Product_Line_Table["SKU"].duplicated(keep=False)]
Product_Line_Table_duplicates
#### Product number and Product Line seems to be different for same SKUs , need to verify other tables before deciding

Empty DataFrame
Columns: [SKU, Product Line, Sub Category]
Index: []

In [230]:
# Remove duplicate SKUs and keep the first occurrence
Product_Line_Table = Product_Line_Table.drop_duplicates(subset=['SKU'], keep='first')

# Reset the index
Product_Line_Table = Product_Line_Table.reset_index(drop=True)

# Check the result
print(Product_Line_Table.shape)
print(Product_Line_Table['SKU'].duplicated().sum())

(1546, 3)
0

In [121]:
Product_Line_Table["Sub Category"] = (Product_Line_Table["Product Line"].str.split("_").str[-1].str.strip())

In [122]:
Product_Line_Table["Sub Category"] = Product_Line_Table["Sub Category"].astype("string").str.strip()

In [232]:
Product_Line_Table["Sub Category"].unique()

<StringArray>
['Laptop', 'Monitor', 'Toner', 'Laser Jet', 'Ink Jet', 'Desktop', 'Ink']
Length: 7, dtype: string

In [124]:
Product_Line_Table["Sub Category"].value_counts()

Sub Category
INK        426
Laptop     416
TON        326
Desktop    164
IJ          84
LJ          74
Monitor     60
UNK         28
SJ          20
Name: count, dtype: Int64

In [125]:
Product_Line_Table["Sub Category"] = Product_Line_Table["Sub Category"].replace({"TON" : "Toner", 
                                                                                 "LJ" : "Laser Jet", 
                                                                                 "IJ":"Ink Jet",
                                                                                "INK" : "Ink"})

In [126]:
Product_Line_Table = Product_Line_Table[
    ~Product_Line_Table['SKU'].isin(SKU_List)
].copy()

In [234]:
Product_Line_Table_cleaned = Product_Line_Table.copy()

In [235]:
Product_Line_Table_cleaned.to_excel(
    r"C:\Data Science\MAP Project\Cleaned files\Product_Line_Table_cleaned.xlsx",
    index=False
)

## 2.c. Price List Table

In [133]:
import yaml

In [134]:
with open("Price List Table.yaml","r") as file: data= yaml.safe_load(file)

In [135]:
type(data)

list

In [136]:
Price_List_Table = pd.DataFrame(data)

In [154]:
Price_List_Table.head()

      MAP       Product Line      SKU  LPP_Price
0  106684   DELL0X_PC_Laptop  0X749QB      98362
1   35611  DELL75_PC_Monitor  75X62BB      33616
2   29914     DELLDF_SUP_TON   DF627B      29225
3   39258         HP4Z_PH_LJ   4ZB96A      36706
4  139670   DELL0R_PC_Laptop  0R0N0QB     128775

In [138]:
Price_List_Table["PL"] = Price_List_Table["PL"].astype("string").str.strip()
Price_List_Table["sku"] = Price_List_Table["sku"].astype("string").str.strip()
Price_List_Table["MAP"] = Price_List_Table["MAP"].astype("int")
Price_List_Table = Price_List_Table.rename(columns={"PL" : "Product Line", "sku" : "SKU"})

In [139]:
print("\nData Types::::::::\n", Price_List_Table.dtypes)
print("\n ***************************************************** \n")
print("\nDescription ::::::::::\n",Price_List_Table.describe(include='all'))
print("\n ***************************************************** \n")
print("\nTotal Null values::::::::\n",Price_List_Table.isnull().sum())
print("\n ***************************************************** \n")
#print("\n Duplicated SKU count:::::::\n",Price_List_Table['SKU'].duplicated().sum())
#print("\n Duplicated Product Number Count:::::::::::\n",Price_List_Table['Product Number'].duplicated().sum())

Data Types::::::::
 MAP              int64
Product Line    string
SKU             string
dtype: object

 *****************************************************


Description ::::::::::
                  MAP    Product Line      SKU
count   1.598000e+03            1598     1598
unique           NaN             428     1594
top              NaN  DELLDG_SUP_TON  8L120PA
freq             NaN              62        2
mean    5.201141e+04             NaN      NaN
std     9.437099e+04             NaN      NaN
min     4.690000e+02             NaN      NaN
25%     6.285750e+03             NaN      NaN
50%     1.707400e+04             NaN      NaN
75%     6.068825e+04             NaN      NaN
max     1.135614e+06             NaN      NaN

 *****************************************************


Total Null values::::::::
 MAP             0
Product Line    0
SKU             0
dtype: int64

 *****************************************************

In [140]:
lpp_file = r"LPP Table.xlsx"

lpp_rates = pd.read_excel(
    lpp_file,
    sheet_name="LPP_Rates"
)

lpp_rates

   Sub Category Category  LPP_Rates
0        Laptop       HP      0.034
1       Monitor       HP      0.012
2         Toner       HP      0.091
3     Laser Jet       HP      0.065
4       Ink Jet       HP      0.012
5       Desktop       HP      0.091
6           Ink       HP      0.065
7        Laptop     DELL      0.078
8       Monitor     DELL      0.056
9         Toner     DELL      0.023
10    Laser Jet     DELL      0.035
11      Ink Jet     DELL      0.056
12      Desktop     DELL      0.023
13          Ink     DELL      0.035
14          UNK       HP      0.000
15           SJ       HP      0.000
16          UNK     DELL      0.000
17           SJ     DELL      0.000

In [141]:
lpp_rates = lpp_rates.rename(columns={"Sub Category" : "Sub Category", "Category" : "Brand", "LPP_Rates" : "LPP_Rates"})

In [142]:
lpp_rates.dtypes

Sub Category        str
Brand               str
LPP_Rates       float64
dtype: object

In [143]:
Price_List_Table["Sub Category"] = (Price_List_Table["Product Line"].str.split("_").str[-1].str.strip())
Price_List_Table["Sub Category"] = Price_List_Table["Sub Category"].astype("string").str.strip()
Price_List_Table["Sub Category"] = Price_List_Table["Sub Category"].replace({"TON" : "Toner", 
                                                                                 "LJ" : "Laser Jet", 
                                                                                 "IJ":"Ink Jet",
                                                                                "INK" : "Ink"})

In [144]:
Price_List_Table

         MAP       Product Line      SKU Sub Category
0     106684   DELL0X_PC_Laptop  0X749QB       Laptop
1      35611  DELL75_PC_Monitor  75X62BB      Monitor
2      29914     DELLDF_SUP_TON   DF627B        Toner
3      39258         HP4Z_PH_LJ   4ZB96A    Laser Jet
4     139670   DELL0R_PC_Laptop  0R0N0QB       Laptop
...      ...                ...      ...          ...
1593    3565     DELL4K_SUP_INK  4KB93BB          Ink
1594    6716     DELLX2_SUP_TON   X2231B        Toner
1595    6868       HPB3_SUP_INK   B3P21A          Ink
1596   47937  DELL78_PC_Desktop  78X20QB      Desktop
1597   28243       HPCF_SUP_TON   CF364A        Toner

[1598 rows x 4 columns]

In [145]:
Price_List_Table["Brand"] = (Price_List_Table["Product Line"].str.extract(r"^(DELL|HP)", expand=False))
Price_List_Table["Brand"] = Price_List_Table["Brand"].astype("string").str.strip()
Price_List_Table["Brand"] = Price_List_Table["Brand"].replace({"Dell" : "DELL", 
                                                                                 "Hp" : "HP"})

In [146]:
Price_List_Table.head()

      MAP       Product Line      SKU Sub Category Brand
0  106684   DELL0X_PC_Laptop  0X749QB       Laptop  DELL
1   35611  DELL75_PC_Monitor  75X62BB      Monitor  DELL
2   29914     DELLDF_SUP_TON   DF627B        Toner  DELL
3   39258         HP4Z_PH_LJ   4ZB96A    Laser Jet    HP
4  139670   DELL0R_PC_Laptop  0R0N0QB       Laptop  DELL

In [147]:
Price_List_Table = Price_List_Table.merge(
    lpp_rates,
    on=["Sub Category", "Brand"],
    how="left"
)

In [148]:
filtered_table = Price_List_Table[Price_List_Table["Sub Category"].isin(["UNK", "SJ"])]
filtered_table

         MAP    Product Line      SKU Sub Category Brand  LPP_Rates
18      7788    HPL0_SUP_UNK  L0R91AA          UNK    HP        0.0
94       528  DELL7A_SUP_UNK  7AE72BB          UNK  DELL        0.0
115    90473    DELL31_PH_SJ   31H19B           SJ  DELL        0.0
206    25856    DELL7G_PH_SJ   7GX17B           SJ  DELL        0.0
235     7897  DELLK4_SUP_UNK   K4N82B          UNK  DELL        0.0
289    10249    HPJ3_SUP_UNK   J3M68A          UNK    HP        0.0
342     8243  DELLM1_SUP_UNK  M1S05BB          UNK  DELL        0.0
370    54367    DELL7G_PH_SJ   7GX10B           SJ  DELL        0.0
372    11434    HPL0_SUP_UNK  L0S06AA          UNK    HP        0.0
424    45395    DELL31_PH_SJ   31H17B           SJ  DELL        0.0
454    30688      HP6F_PH_SJ   6FW07A           SJ    HP        0.0
517    48741      HP6F_PH_SJ   6FW09A           SJ    HP        0.0
539    54502      HP20_PH_SJ   20G07A           SJ    HP        0.0
562    67415      HP6F_PH_SJ   6FW10A           SJ    HP        0.0
617    45789      HP6F_PH_SJ   6FW08A           SJ    HP        0.0
636    12510  DELLM1_SUP_UNK  M1T17BB          UNK  DELL        0.0
640     7879    HPL0_SUP_UNK  L0R88AA          UNK    HP        0.0
684    65166    DELL7G_PH_SJ   7GX21B           SJ  DELL        0.0
685    23550      HP20_PH_SJ   20G05A           SJ    HP        0.0
741    45959      HP20_PH_SJ   20G06A           SJ    HP        0.0
786    11640  DELLK4_SUP_UNK   K4N79B          UNK  DELL        0.0
799    44338    DELL7G_PH_SJ   7GX19B           SJ  DELL        0.0
826    83736      HP20_PH_SJ   20G08A           SJ    HP        0.0
867     8690  DELLM1_SUP_UNK  M1S02BB          UNK  DELL        0.0
950      529    HP6Z_SUP_UNK  6ZD21AA          UNK    HP        0.0
970     8334  DELLM1_SUP_UNK  M1S08BB          UNK  DELL        0.0
976      554  DELL7A_SUP_UNK  7AE32BB          UNK  DELL        0.0
1006   25617      HP6F_PH_SJ   6FW06A           SJ    HP        0.0
1013   10799  DELLK4_SUP_UNK   K4N81B          UNK  DELL        0.0
1017   12083    HPL0_SUP_UNK  L0S00AA          UNK    HP        0.0
1044   11428    HPJ3_SUP_UNK   J3M70A          UNK    HP        0.0
1068   11493  DELLK4_SUP_UNK   K4N70B          UNK  DELL        0.0
1107   11310    HPJ3_SUP_UNK   J3M69A          UNK    HP        0.0
1116  240565    DELLM3_PH_SJ   M3874B           SJ  DELL        0.0
1173    7548    HPJ3_SUP_UNK   J3M71A          UNK    HP        0.0
1191   11434    HPL0_SUP_UNK  L0S03AA          UNK    HP        0.0
1193   12427  DELLM1_SUP_UNK  M1T14BB          UNK  DELL        0.0
1226   12390  DELLM1_SUP_UNK  M1T11BB          UNK  DELL        0.0
1282  223978      HPL2_PH_SJ   L2763A           SJ    HP        0.0
1291     509    HP6Z_SUP_UNK  6ZD61AA          UNK    HP        0.0
1337   11752    HPL0_SUP_UNK  L0S09AA          UNK    HP        0.0
1350    7345    HPL0_SUP_UNK  L0R97AA          UNK    HP        0.0
1401    8361  DELLM1_SUP_UNK  M1S99BB          UNK  DELL        0.0
1413   12485  DELLM1_SUP_UNK  M1T10BB          UNK  DELL        0.0
1454    8060    HPL0_SUP_UNK  L0R94AA          UNK    HP        0.0
1514   34575    DELL7G_PH_SJ   7GX18B           SJ  DELL        0.0
1534   24266    DELL31_PH_SJ   31H16B           SJ  DELL        0.0
1542   63318    DELL31_PH_SJ   31H18B           SJ  DELL        0.0

In [149]:
Price_List_Table["LPP_Price"] = (
    Price_List_Table["MAP"]
    - Price_List_Table["MAP"] * Price_List_Table["LPP_Rates"]
)

In [150]:
Price_List_Table["LPP_Price"] = Price_List_Table["LPP_Price"].astype("int")

In [151]:
Price_List_Table = Price_List_Table.drop(
    columns=["Brand", "Sub Category", "LPP_Rates"]
)

In [152]:
SKU_List = filtered_table['SKU'].tolist()

In [153]:
Price_List_Table = Price_List_Table[
    ~Price_List_Table['SKU'].isin(SKU_List)
].copy()

In [238]:
Price_List_Table_cleaned = Price_List_Table.copy()

In [239]:
Price_List_Table_cleaned.to_excel(r"C:\Data Science\MAP Project\Cleaned files\Price_List_Table_cleaned.xlsx", index=False)

In [237]:
# Remove duplicate SKUs and keep the first occurrence
Price_List_Table = Price_List_Table.drop_duplicates(subset=['SKU'], keep='first')

# Reset the index
Price_List_Table = Price_List_Table.reset_index(drop=True)

# Check the result
print(Price_List_Table.shape)
print(Price_List_Table['SKU'].duplicated().sum())

(1546, 4)
0

## 2.d. Seller Mapping Table

In [48]:
Seller_Mapping_Table = pd.read_excel("Seller Mapping Table.xlsx")

In [56]:
Seller_Mapping_Table.head()

       Advertised Seller Name         Actual Seller
0              Cocoblu Retail   BJ's Wholesale Club
1    RK World Infocom Pvt Ltd        American Eagle
2  Appario Retail Private Ltd              Tapestry
3            RetailEZ Pvt Ltd   Wakefern / ShopRite
4               ETrade Online  Harbor Freight Tools

In [50]:
Seller_Mapping_Table["Ssellers_name"] = Seller_Mapping_Table["Ssellers_name"].astype("string").str.strip()
Seller_Mapping_Table["homologated_sellers"] = Seller_Mapping_Table["homologated_sellers"].astype("string").str.strip()
Seller_Mapping_Table = Seller_Mapping_Table.rename(columns={"Ssellers_name" : "Advertised Seller Name",
                                                            "homologated_sellers" : "Actual Seller"})

In [57]:
print("\nData Types::::::::\n", Seller_Mapping_Table.dtypes)
print("\n ***************************************************** \n")
print("\nDescription ::::::::::\n",Seller_Mapping_Table.describe(include='all'))
print("\n ***************************************************** \n")
print("\nTotal Null values::::::::\n",Seller_Mapping_Table.isnull().sum())
print("\n ***************************************************** \n")
print("\n Duplicated Advertised seller name:::::::\n",Seller_Mapping_Table['Advertised Seller Name'].duplicated().sum())
print("\n Duplicated Actual seller name:::::::::::\n",Seller_Mapping_Table['Actual Seller'].duplicated().sum())

Data Types::::::::
 Advertised Seller Name    string
Actual Seller             string
dtype: object

 *****************************************************


Description ::::::::::
        Advertised Seller Name Actual Seller
count                     903           903
unique                    903           100
top            Cocoblu Retail      Tapestry
freq                        1            10

 *****************************************************


Total Null values::::::::
 Advertised Seller Name    0
Actual Seller             0
dtype: int64

 *****************************************************


 Duplicated Advertised seller name:::::::
 0

 Duplicated Actual seller name:::::::::::
 803

In [58]:
Seller_duplicates = Seller_Mapping_Table[Seller_Mapping_Table["Advertised Seller Name"].duplicated(keep=False)]
Seller_duplicates

Empty DataFrame
Columns: [Advertised Seller Name, Actual Seller]
Index: []

In [53]:
Seller_Mapping_Table.loc[ Seller_Mapping_Table["Advertised Seller Name"] == "Seller", "Advertised Seller Name"] = ["Sprouts Farmers Market", "7-Eleven","Tractor Supply Co."]

In [54]:
Seller_Mapping_Table[Seller_Mapping_Table["Actual Seller"] == "7-Eleven"]

                         Advertised Seller Name Actual Seller
28                             FAMILY FOOTWEAR.      7-Eleven
192                         ELEMENT ENTERPRISES      7-Eleven
218                           Smart Place Store      7-Eleven
301                                    7-Eleven      7-Eleven
490                 WEWEL PLAST PRIVATE LIMITED      7-Eleven
504  Navashya Consumer Products Private Limited      7-Eleven
610                             The Old Natural      7-Eleven
790                               Primarc Pecan      7-Eleven
885                                     Dingger      7-Eleven

In [55]:
type(Seller_Mapping_Table)

pandas.DataFrame

In [161]:
Seller_Mapping_Table_cleaned = Seller_Mapping_Table.copy()

In [162]:
Seller_Mapping_Table_cleaned.to_excel(r"C:\Data Science\MAP Project\Cleaned files\Seller_Mapping_Table_cleaned.xlsx", index=False)

## 2.e. Category mapping Table

In [59]:
Category_Mapping_Table = pd.read_json("Category Mapping Table.json", lines=True)

In [163]:
Category_Mapping_Table.head()

        Product Line      SKU         Category Sub Category
0   DELL0X_PC_Laptop  0X749QB               PC       Laptop
1  DELL75_PC_Monitor  75X62BB               PC      Monitor
2     DELLDF_SUP_TON   DF627B  Supply Hardware        Toner
3         HP4Z_PH_LJ   4ZB96A   Print Hardware    Laser Jet
4   DELL0R_PC_Laptop  0R0N0QB               PC       Laptop

In [61]:
print("\nData Types::::::::\n", Category_Mapping_Table.dtypes)
print("\n ***************************************************** \n")
print("\nDescription ::::::::::\n",Category_Mapping_Table.describe(include='all'))
print("\n ***************************************************** \n")
print("\nTotal Null values::::::::\n",Category_Mapping_Table.isnull().sum())
print("\n ***************************************************** \n")

Data Types::::::::
 PL     str
sku    str
dtype: object

 *****************************************************


Description ::::::::::
                     PL      sku
count             1598     1598
unique             428     1594
top     DELLDG_SUP_TON  8L120PA
freq                62        2

 *****************************************************


Total Null values::::::::
 PL     0
sku    0
dtype: int64

 *****************************************************

In [62]:
Category_Mapping_Table["Category"] = (Category_Mapping_Table["PL"].str.split("_").str[1])
Category_Mapping_Table["Sub Category"] = (Category_Mapping_Table["PL"].str.split("_").str[-1])

In [63]:
Category_Mapping_Table["sku"] = Category_Mapping_Table["sku"].astype("string").str.strip()
Category_Mapping_Table["PL"] = Category_Mapping_Table["PL"].astype("string").str.strip()
Category_Mapping_Table = Category_Mapping_Table.rename(columns={ "PL" : "Product Line", "sku" : "SKU" })

In [64]:
print(Category_Mapping_Table["Category"].unique())
print(Category_Mapping_Table["Sub Category"].unique())

['PC' 'SUP' 'PH']
['Laptop' 'Monitor' 'TON' 'LJ' 'IJ' 'Desktop' 'INK' 'UNK' 'SJ']

In [65]:
Category_Mapping_Table["Sub Category"] = Category_Mapping_Table["Sub Category"].replace({"TON" : "Toner", 
                                                                                 "LJ" : "Laser Jet", 
                                                                                 "IJ":"Ink Jet",
                                                                                "INK" : "Ink"})
Category_Mapping_Table["Category"] = Category_Mapping_Table["Category"].replace({"SUP" : "Supply Hardware", 
                                                                                 "PH" : "Print Hardware", 
                                                                                 "PC":"PC"})

In [66]:
Category_Mapping_Table_duplicates = Category_Mapping_Table[Category_Mapping_Table["SKU"].duplicated(keep=False)]
Category_Mapping_Table_duplicates

         Product Line      SKU Category Sub Category
130    HP8L_PC_Laptop  8L120PA       PC       Laptop
482   HP8L_PC_Desktop  8L129PA       PC      Desktop
900   HP8L_PC_Desktop  8L130PA       PC      Desktop
1023  HP8L_PC_Desktop  8L120PA       PC      Desktop
1056   HP8L_PC_Laptop  8L129PA       PC       Laptop
1247   HP8F_PC_Laptop  8F6D4PA       PC       Laptop
1309   HP8L_PC_Laptop  8L130PA       PC       Laptop
1356  HP8F_PC_Desktop  8F6D4PA       PC      Desktop

In [67]:
Category_Mapping_Table["Sub Category"].value_counts()

Sub Category
Ink          426
Laptop       416
Toner        326
Desktop      164
Ink Jet       84
Laser Jet     74
Monitor       60
UNK           28
SJ            20
Name: count, dtype: int64

In [68]:
PC_subcategories = Category_Mapping_Table.loc[
    Category_Mapping_Table["Category"] == "PC",
    "Sub Category"
].unique()

print(PC_subcategories)

['Laptop' 'Monitor' 'Desktop']

In [69]:
PH_subcategories = Category_Mapping_Table.loc[
    Category_Mapping_Table["Category"] == "Print Hardware",
    "Sub Category"
].unique()

print(PH_subcategories)

['Laser Jet' 'Ink Jet' 'SJ']

In [70]:
SUP_subcategories = Category_Mapping_Table.loc[
    Category_Mapping_Table["Category"] == "Supply Hardware",
    "Sub Category"
].unique()

print(SUP_subcategories)

['Toner' 'Ink' 'UNK']

In [71]:
Category_Mapping_Table = Category_Mapping_Table[
    ~Category_Mapping_Table['SKU'].isin(SKU_List)
].copy()

In [241]:
Category_Mapping_Table_cleaned = Category_Mapping_Table.copy()

In [242]:
Category_Mapping_Table_cleaned.to_excel(r"C:\Data Science\MAP Project\Cleaned files\Category_Mapping_Table_cleaned.xlsx", index=False)

In [240]:
# Remove duplicate SKUs and keep the first occurrence
Category_Mapping_Table = Category_Mapping_Table.drop_duplicates(subset=['SKU'], keep='first')

# Reset the index
Category_Mapping_Table = Category_Mapping_Table.reset_index(drop=True)

# Check the result
print(Category_Mapping_Table.shape)
print(Category_Mapping_Table['SKU'].duplicated().sum())

(1546, 4)
0

## 2.f. Promotion Table

In [73]:
Promotion_Table = pd.read_json("Product Line Table.json",lines=True)

In [99]:
Promotion_Table.head()

       SKU       Product Line Season  Promotion
0  0X749QB   DELL0X_PC_Laptop     Q4          0
1  75X62BB  DELL75_PC_Monitor     Q4          0
2   DF627B     DELLDF_SUP_TON     Q4          0
3   4ZB96A         HP4Z_PH_LJ     Q4          0
4  0R0N0QB   DELL0R_PC_Laptop     Q4          0

In [75]:
Promotion_Table["sku"] = Promotion_Table["sku"].astype("string").str.strip()
Promotion_Table["PL"] = Promotion_Table["PL"].astype("string").str.strip()
Promotion_Table = Promotion_Table.rename(columns={ "sku" : "SKU","PL" : "Product Line"})

In [76]:
print("\nData Types::::::::\n", Promotion_Table.dtypes)
print("\n ***************************************************** \n")
print("\nDescription ::::::::::\n",Promotion_Table.describe(include='all'))
print("\n ***************************************************** \n")
print("\nTotal Null values::::::::\n",Promotion_Table.isnull().sum())
print("\n ***************************************************** \n")
print("\n Duplicated SKU count:::::::\n",Promotion_Table['SKU'].duplicated().sum())

Data Types::::::::
 SKU             string
Product Line    string
dtype: object

 *****************************************************


Description ::::::::::
             SKU    Product Line
count      1598            1598
unique     1594             428
top     8L120PA  DELLDG_SUP_TON
freq          2              62

 *****************************************************


Total Null values::::::::
 SKU             0
Product Line    0
dtype: int64

 *****************************************************


 Duplicated SKU count:::::::
 4

In [77]:
Promotion_Table = Promotion_Table[
    ~Promotion_Table['SKU'].isin(SKU_List)
].copy()

In [77]:
filtered_table = Category_Mapping_Table[Category_Mapping_Table["Sub Category"].isin(["UNK", "SJ"])]

In [78]:
filtered_table

Empty DataFrame
Columns: [Product Line, SKU, Category, Sub Category]
Index: []

In [79]:
filtered_table['SKU'].nunique()

0

In [78]:
from datetime import datetime
Promotion_Sheet = r"Promotion Table.xlsx"
Season_Mapping = pd.read_excel(Promotion_Sheet, sheet_name="Season Map")
Season_Mapping

    Month_Number Season
0              1     Q1
1              2     Q2
2              3     Q2
3              4     Q2
4              5     Q3
5              6     Q3
6              7     Q3
7              8     Q4
8              9     Q4
9             10     Q4
10            11     Q1
11            12     Q1

In [79]:
current_month = datetime.now().month
current_month

10

In [80]:
current_season = Season_Mapping.loc[
    Season_Mapping["Month_Number"] == current_month,
    "Season"
].iloc[0]
current_season

'Q4'

In [81]:
Promotion_Table["Season"] = current_season

In [82]:
Promotion_Table["Season"].nunique()

1

In [83]:
Offer_Rules = pd.read_excel(
    "Promotion Table.xlsx",
    sheet_name="Offer_Rules")

In [84]:
Offer_Rules.dtypes

Category              object
Season                   str
Offer Description        str
Offer Type               str
Sub Category             str
Offer Value          float64
dtype: object

In [85]:
for col in ["Category", "Season", "Sub Category", "Offer Type"]:
    Offer_Rules[col] = (
        Offer_Rules[col]
        .astype("string")
        .str.strip()
    )

In [86]:
Eligible_SKUs = pd.read_excel(
    "Promotion Table.xlsx",
    sheet_name="Eligible_SKUs"
)

In [87]:
Eligible_SKUs["Eligible_SKUs"] = (
    Eligible_SKUs["Eligible_SKUs"]
    .astype("string")
    .str.strip()
)

In [88]:
# Merge Category and Sub Category
Promotion_Table = Promotion_Table.merge(
    Category_Mapping_Table[['Product Line', 'SKU', 'Category', 'Sub Category']],
    on=['Product Line', 'SKU'],
    how='left'
)

# Merge MAP
Promotion_Table = Promotion_Table.merge(
    Price_List_Table[['Product Line', 'SKU', 'MAP']],
    on=['Product Line', 'SKU'],
    how='left'
)

# Display the updated Promotion_Table
Promotion_Table.head()

       SKU       Product Line Season         Category Sub Category     MAP
0  0X749QB   DELL0X_PC_Laptop     Q4               PC       Laptop  106684
1  75X62BB  DELL75_PC_Monitor     Q4               PC      Monitor   35611
2   DF627B     DELLDF_SUP_TON     Q4  Supply Hardware        Toner   29914
3   4ZB96A         HP4Z_PH_LJ     Q4   Print Hardware    Laser Jet   39258
4  0R0N0QB   DELL0R_PC_Laptop     Q4               PC       Laptop  139670

In [89]:
Promotion_Table["SKU_Eligible"] = (
    Promotion_Table["SKU"]
    .isin(Eligible_SKUs["Eligible_SKUs"])
)

In [90]:
Promotion_Table.head()

,SKU,Product Line,Season,Category,Sub Category,MAP,SKU_Eligible
0,0X749QB,DELL0X_PC_Laptop,Q4,PC,Laptop,106684,False
1,75X62BB,DELL75_PC_Monitor,Q4,PC,Monitor,35611,False
2,DF627B,DELLDF_SUP_TON,Q4,Supply Hardware,Toner,29914,False
3,4ZB96A,HP4Z_PH_LJ,Q4,Print Hardware,Laser Jet,39258,False
4,0R0N0QB,DELL0R_PC_Laptop,Q4,PC,Laptop,139670,False

In [91]:
Promotion_Table["SKU_Eligible"].value_counts()

SKU_Eligible
False    1454
True       96
Name: count, dtype: int64

In [92]:
def calculate_promotion(row):

    # 1. SKU must be eligible
    if not row["SKU_Eligible"]:
        return 0

    # 2. Find matching offer rules
    matching_rules = Offer_Rules[
        (Offer_Rules["Season"] == row["Season"]) &
        (Offer_Rules["Category"] == row["Category"])
    ]

    # 3. Check sub-category
    matching_rules = matching_rules[
        (matching_rules["Sub Category"].isna()) |
        (matching_rules["Sub Category"] == row["Sub Category"])
    ]

    # 4. No matching promotion
    if matching_rules.empty:
        return 0

    # 5. Get the matching offer
    offer = matching_rules.iloc[0]

    # 6. Calculate promotion
    if offer["Offer Type"] == "Percentage":
        return row["MAP"] * offer["Offer Value"]

    elif offer["Offer Type"] == "Fixed":
        return offer["Offer Value"]

    return 0

In [93]:
Promotion_Table["Promotion"] = (
    Promotion_Table.apply(
        calculate_promotion,
        axis=1
    )
)

In [94]:
Promotion_Table.head()

,SKU,Product Line,Season,Category,Sub Category,MAP,SKU_Eligible,Promotion
0,0X749QB,DELL0X_PC_Laptop,Q4,PC,Laptop,106684,False,0.0
1,75X62BB,DELL75_PC_Monitor,Q4,PC,Monitor,35611,False,0.0
2,DF627B,DELLDF_SUP_TON,Q4,Supply Hardware,Toner,29914,False,0.0
3,4ZB96A,HP4Z_PH_LJ,Q4,Print Hardware,Laser Jet,39258,False,0.0
4,0R0N0QB,DELL0R_PC_Laptop,Q4,PC,Laptop,139670,False,0.0

In [95]:
Promotion_Table["Promotion"] = Promotion_Table["Promotion"].astype("int")

In [96]:
Promotion_Table.dtypes

SKU             string
Product Line    string
Season             str
Category        object
Sub Category    object
MAP              int64
SKU_Eligible      bool
Promotion        int64
dtype: object

In [97]:
Promotion_Table["SKU_Eligible"] == True

0       False
1       False
2       False
3       False
4       False
        ...
1545    False
1546    False
1547     True
1548    False
1549    False
Name: SKU_Eligible, Length: 1550, dtype: bool

In [98]:
Promotion_Table = Promotion_Table.drop(
    columns=["Category", "Sub Category", "MAP" , "SKU_Eligible"]
)

In [244]:
Promotion_Table_cleaned = Promotion_Table.copy()

In [245]:
Promotion_Table_cleaned.to_excel(r"C:\Data Science\MAP Project\Cleaned files\Promotion_Table_cleaned.xlsx", index=False)

In [243]:
# Remove duplicate SKUs and keep the first occurrence
Promotion_Table = Promotion_Table.drop_duplicates(subset=['SKU'], keep='first')

# Reset the index
Promotion_Table = Promotion_Table.reset_index(drop=True)

# Check the result
print(Promotion_Table.shape)
print(Promotion_Table['SKU'].duplicated().sum())

(1546, 4)
0

## SQL lOADING

In [145]:
%pip install mysql-connector-python sqlalchemy

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.54-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: greenlet>=1 in C:\Users\varun\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\varun\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading mysql_connector_python-26.7.0-cp314-cp314-win_amd64.whl (18.2 MB)
   ---------------------------------------- 0.0/18.2 MB ? eta -:--:--
   --- ------------------------------------ 1.6/18.2 MB 13.4 MB/s eta 0:00:02
   --------- ------------------------------ 4.5/18.2 MB 13.1 MB/s eta 0:00:02
   ---------------- ----------------------- 7.3/18.2 MB 13.8 MB/s eta 0:00:01
   ---------------------- ----------------- 10.2/18.2 MB 13.9 MB/s eta 0:00:01
   ---------------------------- ----------- 13.1/18.2 MB 13.8 MB/s eta 0:00:01
   ----------------------------------- ---- 16.0/18.2 MB 13.9 MB/s eta 0:00:01
   ---------------------------------------  18.1/18.2 MB 14.0 MB/s eta 0:00:01
   ---------------------------------------- 18.2/18.2 MB 12.1 MB/s  0:00:01
Downloading sqlalchemy-2.0.54-cp314-cp314-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 2.2/2.2 MB 11.6 MB/s  0:00:00
Installing collected packages: sqlalchemy, mysql-connector-python

   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   ---------------------------------------- 0/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   -------------------- ------------------- 1/2 [mysql-connector-python]
   ---------------------------------------- 2/2 [mysql-connector-python]

Successfully installed mysql-connector-python-26.7.0 sqlalchemy-2.0.54
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [146]:
import mysql.connector
from sqlalchemy import create_engine

In [147]:
# MySQL connection
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Varun2&vibhu"
)

cursor = connection.cursor()

# Create database
cursor.execute("CREATE DATABASE IF NOT EXISTS MAP_data")

cursor.close()
connection.close()

print("Database MAP_data created successfully.")

Database MAP_data created successfully.

In [159]:
engine = create_engine(
    "mysql+mysqlconnector://root:Varun2%26vibhu@localhost/MAP_data"
)

print("Connected to MAP_data successfully.")

Connected to MAP_data successfully.

In [160]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Varun2&vibhu",
    database="MAP_data"
)

cursor = connection.cursor()

### create SKU_Table

In [150]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS SKU_Table (
    `Product Number` VARCHAR(50) NOT NULL,
    `SKU` VARCHAR(50) NOT NULL,
    
    UNIQUE KEY `uq_product_number` (`Product Number`)
)
""")

### Create Product_Line_Table

In [151]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Product_Line_Table (
    `SKU` VARCHAR(50) NOT NULL,
    `Product Line` VARCHAR(50) NOT NULL,
    `Sub Category` VARCHAR(30),
    
    PRIMARY KEY (`Product Line`, `SKU`)
)
""")

### Create Price_List_Table

In [152]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Price_List_Table (
    `MAP` DECIMAL(15,2),
    `Product Line` VARCHAR(50) NOT NULL,
    `SKU` VARCHAR(50) NOT NULL,
    `LPP_Price` DECIMAL(15,2),

    CONSTRAINT `fk_price_list_product_line`
        FOREIGN KEY (`Product Line`, `SKU`)
        REFERENCES Product_Line_Table (`Product Line`, `SKU`)
)
""")

### Create Seller_Mapping_Table

In [161]:
cursor.execute("DROP TABLE IF EXISTS Seller_Mapping_Table")

In [162]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Seller_Mapping_Table (
    `Advertised Seller Name` VARCHAR(100) NOT NULL,
    `Actual Seller` VARCHAR(100) NOT NULL,
    
    UNIQUE KEY `uq_actual_seller` (`Advertised Seller Name`)
)
""")

### Create Category_Mapping_Table

In [154]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Category_Mapping_Table (
    `Product Line` VARCHAR(50) NOT NULL,
    `SKU` VARCHAR(50) NOT NULL,
    `Category` VARCHAR(30),
    `Sub Category` VARCHAR(30),

    CONSTRAINT `fk_category_mapping_product_line`
        FOREIGN KEY (`Product Line`, `SKU`)
        REFERENCES Product_Line_Table (`Product Line`, `SKU`)
)
""")

### create Promotion_Table

In [155]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Promotion_Table (
    `SKU` VARCHAR(50) NOT NULL,
    `Product Line` VARCHAR(50) NOT NULL,
    `Season` VARCHAR(20),
    `Promotion` DECIMAL(15,2),

    CONSTRAINT `fk_promotion_product_line`
        FOREIGN KEY (`Product Line`, `SKU`)
        REFERENCES Product_Line_Table (`Product Line`, `SKU`)
)
""")

In [163]:
connection.commit()

cursor.close()
connection.close()

print("All MAP tables created successfully.")

All MAP tables created successfully.

In [164]:
# Parent table first
Product_Line_Table.to_sql(
    "Product_Line_Table",
    con=engine,
    if_exists="append",
    index=False
)

# Child tables
Price_List_Table.to_sql(
    "Price_List_Table",
    con=engine,
    if_exists="append",
    index=False
)

Category_Mapping_Table.to_sql(
    "Category_Mapping_Table",
    con=engine,
    if_exists="append",
    index=False
)

Promotion_Table.to_sql(
    "Promotion_Table",
    con=engine,
    if_exists="append",
    index=False
)

# Independent tables
SKU_Table.to_sql(
    "SKU_Table",
    con=engine,
    if_exists="append",
    index=False
)

Seller_Mapping_Table.to_sql(
    "Seller_Mapping_Table",
    con=engine,
    if_exists="append",
    index=False
)

print("All tables loaded successfully.")

DatabaseError: Execution failed on sql 'INSERT INTO "Product_Line_Table" ("SKU", "Product Line", "Sub Category") VALUES (:SKU, :Product_Line, :Sub_Category)': (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'DELL0X_PC_Laptop-0X749QB' for key 'product_line_table.PRIMARY'
[SQL: INSERT INTO `Product_Line_Table` (`SKU`, `Product Line`, `Sub Category`) VALUES (%(SKU)s, %(Product_Line)s, %(Sub_Category)s)]
[parameters: [{'SKU': '0X749QB', 'Product_Line': 'DELL0X_PC_Laptop', 'Sub_Category': 'Laptop'}, {'SKU': '75X62BB', 'Product_Line': 'DELL75_PC_Monitor', 'Sub_Category': 'Monitor'}, {'SKU': 'DF627B', 'Product_Line': 'DELLDF_SUP_TON', 'Sub_Category': 'Toner'}, {'SKU': '4ZB96A', 'Product_Line': 'HP4Z_PH_LJ', 'Sub_Category': 'Laser Jet'}, {'SKU': '0R0N0QB', 'Product_Line': 'DELL0R_PC_Laptop', 'Sub_Category': 'Laptop'}, {'SKU': '7LE37B', 'Product_Line': 'DELL7L_PH_IJ', 'Sub_Category': 'Ink Jet'}, {'SKU': '89Z55QB', 'Product_Line': 'DELL89_PC_Desktop', 'Sub_Category': 'Desktop'}, {'SKU': '8C4R9PA', 'Product_Line': 'HP8C_PC_Laptop', 'Sub_Category': 'Laptop'}  ... displaying 10 of 1550 total bound parameter sets ...  {'SKU': '78X20QB', 'Product_Line': 'DELL78_PC_Desktop', 'Sub_Category': 'Desktop'}, {'SKU': 'CF364A', 'Product_Line': 'HPCF_SUP_TON', 'Sub_Category': 'Toner'}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [167]:
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Varun2&vibhu",
    database="MAP_data"
)

cursor = connection.cursor()

cursor.execute("SHOW TABLES")

for table in cursor.fetchall():
    print(table[0])

cursor.close()
connection.close()

category_mapping_table
price_list_table
product_line_table
promotion_table
seller_mapping_table
sku_table

In [165]:
Seller_Mapping_Table.to_sql(
    "Seller_Mapping_Table",
    con=engine,
    if_exists="append",
    index=False
)

C:\Users\varun\AppData\Local\Temp\ipykernel_19616\3922183750.py:1: UserWarning: The provided table name 'Seller_Mapping_Table' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Seller_Mapping_Table.to_sql(

903

## 2.g. Seller Table

### web scrapping

In [134]:
#!pip install pandas playwright
#!playwright install chromium

Downloading Chrome for Testing 153.0.8010.12 (playwright chromium v1243) from https://cdn.playwright.dev/builds/cft/153.0.8010.12/win64/chrome-win64.zip
|                                                                                |   0% of 195.6 MiB
|â– â– â– â– â– â– â– â–                                                                         |  10% of 195.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                                 |  20% of 195.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                         |  30% of 195.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                 |  40% of 195.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                         |  50% of 195.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                 |  60% of 195.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                         |  70% of 195.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                 |  80% of 195.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–         |  90% of 195.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– | 100% of 195.6 MiB
Chrome for Testing 153.0.8010.12 (playwright chromium v1243) downloaded to C:\Users\varun\AppData\Local\ms-playwright\chromium-1243
Downloading FFmpeg (playwright ffmpeg v1011) from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-win64.zip
|                                                                                |   1% of 1.3 MiB
|â– â– â– â– â– â– â– â–                                                                         |  10% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                                 |  20% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                         |  30% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                 |  40% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                         |  51% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                 |  61% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                         |  70% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                 |  80% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–         |  90% of 1.3 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– | 100% of 1.3 MiB
FFmpeg (playwright ffmpeg v1011) downloaded to C:\Users\varun\AppData\Local\ms-playwright\ffmpeg-1011
Downloading Chrome Headless Shell 153.0.8010.12 (playwright chromium-headless-shell v1243) from https://cdn.playwright.dev/builds/cft/153.0.8010.12/win64/chrome-headless-shell-win64.zip
|                                                                                |   0% of 114.6 MiB
|â– â– â– â– â– â– â– â–                                                                         |  10% of 114.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                                 |  20% of 114.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                         |  30% of 114.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                 |  40% of 114.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                         |  50% of 114.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                 |  60% of 114.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                         |  70% of 114.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                 |  80% of 114.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–         |  90% of 114.6 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– | 100% of 114.6 MiB
Chrome Headless Shell 153.0.8010.12 (playwright chromium-headless-shell v1243) downloaded to C:\Users\varun\AppData\Local\ms-playwright\chromium_headless_shell-1243
Downloading Winldd (playwright winldd v1007) from https://cdn.playwright.dev/dbazure/download/playwright/builds/winldd/1007/winldd-win64.zip
|â– â– â– â– â– â– â– â–                                                                         |  12% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                                 |  25% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                                         |  38% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                                         |  51% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                         |  70% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â–                 |  82% of 0.1 MiB
|â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– | 100% of 0.1 MiB
Winldd (playwright winldd v1007) downloaded to C:\Users\varun\AppData\Local\ms-playwright\winldd-1007

In [138]:
import pandas as pd
from playwright.async_api import async_playwright
import re
import os
from datetime import datetime


# --------------------------------------------------
# 1. Amazon URLs
# --------------------------------------------------

urls = [
    "https://www.amazon.com/Laptop-Computer-N4020-128GB-Windows/dp/B0H5BTZFC1",
    "https://www.amazon.com/Lenovo-Business-Laptop-Processor-Storage/dp/B0HFJ9BNPL",
    "https://www.amazon.com/HP-LaserJet-M140w-Wireless-Printer/dp/B09MSPNYQ2",
    "https://www.amazon.com/Brother-HL-L2405W-Monochrome-Subscription-Replenishment/dp/B0CPL7HRQN",
    "https://www.amazon.com/HP-Toner-Cartridge-Black-W2110A/dp/B0843HSL56",
    "https://www.amazon.com/Brother-Genuine-Cartridge-TN830XL-Yield/dp/B0BX2G5K2G"
]


# --------------------------------------------------
# 2. Create screenshot folder
# --------------------------------------------------

os.makedirs("amazon_screenshots", exist_ok=True)


# --------------------------------------------------
# 3. Function to extract ASIN
# --------------------------------------------------

def extract_asin(url):

    match = re.search(r"/dp/([A-Z0-9]{10})", url)

    if match:
        return match.group(1)

    return None


# --------------------------------------------------
# 4. Async scraping function
# --------------------------------------------------

async def scrape_amazon_products(urls):

    records = []

    async with async_playwright() as p:

        browser = await p.chromium.launch(headless=True)

        page = await browser.new_page()

        # Loop through all 6 URLs
        for i, url in enumerate(urls, start=1):

            print(f"\nScraping product {i} of {len(urls)}")
            print("URL:", url)

            try:

                # ------------------------------------------
                # Open Amazon product page
                # ------------------------------------------

                await page.goto(
                    url,
                    wait_until="domcontentloaded",
                    timeout=60000
                )

                # Give Amazon some time to load dynamic content
                await page.wait_for_timeout(3000)


                # ------------------------------------------
                # SKU / ASIN
                # ------------------------------------------

                sku = extract_asin(url)


                # ------------------------------------------
                # Seller name
                # ------------------------------------------

                seller_name = None

                seller_selectors = [
                    "#sellerProfileTriggerId",
                    "#merchant-info a",
                    "#merchant-info",
                    "#tabular-buybox .tabular-buybox-text",
                    "#buybox .a-size-small"
                ]

                for selector in seller_selectors:

                    element = await page.query_selector(selector)

                    if element:

                        text = await element.inner_text()

                        if text.strip():

                            seller_name = text.strip()

                            break


                # ------------------------------------------
                # Advertised price
                # ------------------------------------------

                advertised_price = None

                price_selectors = [
                    "#corePrice_feature_div .a-price .a-offscreen",
                    "#corePriceDisplay_desktop_feature_div .a-price .a-offscreen",
                    "#priceblock_ourprice",
                    "#priceblock_dealprice",
                    ".a-price .a-offscreen"
                ]

                for selector in price_selectors:

                    element = await page.query_selector(selector)

                    if element:

                        text = await element.inner_text()

                        if text.strip():

                            advertised_price = text.strip()

                            break


                # ------------------------------------------
                # Region
                # ------------------------------------------

                region = "US"


                # ------------------------------------------
                # Marketplace
                # ------------------------------------------

                marketplace = "Amazon.com"


                # ------------------------------------------
                # Last time collected
                # ------------------------------------------

                last_time_collected = datetime.now().strftime(
                    "%Y-%m-%d %H:%M:%S"
                )


                # ------------------------------------------
                # Screenshot
                # ------------------------------------------

                screenshot_path = (
                    f"amazon_screenshots/"
                    f"product_{i}_{sku}.png"
                )

                await page.screenshot(
                    path=screenshot_path,
                    full_page=True
                )


                # ------------------------------------------
                # Store result
                # ------------------------------------------

                records.append({

                    "Seller_name": seller_name,

                    "SKU": sku,

                    "Region": region,

                    "Advertised_price": advertised_price,

                    "Marketplace": marketplace,

                    "Screenshot": screenshot_path,

                    "Live_link": page.url,

                    "Last_time_collected": last_time_collected
                })


                print("Seller:", seller_name)
                print("SKU:", sku)
                print("Price:", advertised_price)
                print("Status: Success")


            except Exception as e:

                print("Error:", e)

                # Still create a row for this product
                records.append({

                    "Seller_name": None,

                    "SKU": extract_asin(url),

                    "Region": "US",

                    "Advertised_price": None,

                    "Marketplace": "Amazon.com",

                    "Screenshot": None,

                    "Live_link": url,

                    "Last_time_collected":
                        datetime.now().strftime(
                            "%Y-%m-%d %H:%M:%S"
                        )
                })


        # ------------------------------------------
        # Close browser
        # ------------------------------------------

        await browser.close()


    # ------------------------------------------
    # Create DataFrame
    # ------------------------------------------

    Seller_Table = pd.DataFrame(records)

    return Seller_Table

In [142]:
Seller_Table = await scrape_amazon_products(urls)

NotImplementedError:

In [141]:
Seller_Table

### seller files consolidation and cleaning

In [135]:
import pandas as pd
from pathlib import Path
import re


# --------------------------------------------------
# 1. FOLDER LOCATION
# --------------------------------------------------

folder_path = Path(r"C:\Data Science/MAP Project/Seller Files")


# --------------------------------------------------
# 2. FUNCTION TO EXTRACT DATE FROM FILE NAME
# --------------------------------------------------

def extract_date_from_filename(file_name):

    # Looks for dates such as:
    # 2026-09-27
    # 2026_09_27
    # 2026.09.27

    match = re.search(
        r"(\d{4})[-_.](\d{2})[-_.](\d{2})",
        file_name
    )

    if match:
        date_string = "-".join(match.groups())
        return pd.to_datetime(date_string)

    return pd.NaT


# --------------------------------------------------
# 3. FUNCTION TO CLEAN EACH CSV FILE
# --------------------------------------------------

def clean_seller_file(file_path):

    # Read CSV
    df = pd.read_csv(file_path)

    # Clean column names
    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )

    # Rename columns
    df = df.rename(columns={
        "Seller_name": "Seller_Name",
        "adv_price": "Advertised_Price",
        "Marketplace": "Marketplace",
        "region": "Region",
        "SKU": "SKU"
    })

    # Drop unwanted columns
    df = df.drop(
        columns=["Screenshot", "live_link"],
        errors="ignore"
    )

    # Remove completely empty rows
    df = df.dropna(how="all")

    # --------------------------------------------------
    # Clean text columns
    # --------------------------------------------------

    text_columns = [
        "SKU",
        "Marketplace",
        "Seller_Name",
        "Region"
    ]

    for col in text_columns:
        if col in df.columns:
            df[col] = (
                df[col]
                .astype("string")
                .str.strip()
            )

    # --------------------------------------------------
    # Clean Advertised Price
    # --------------------------------------------------

    if "Advertised_Price" in df.columns:

        df["Advertised_Price"] = (
            df["Advertised_Price"]
            .astype("string")
            .str.replace("$", "", regex=False)
            .str.replace(",", "", regex=False)
            .str.strip()
        )

        df["Advertised_Price"] = pd.to_numeric(
            df["Advertised_Price"],
            errors="coerce"
        )

    # --------------------------------------------------
    # Add Violation Date from filename
    # --------------------------------------------------

    df["Violation_Date"] = extract_date_from_filename(
        file_path.name
    )

    return df


# --------------------------------------------------
# 4. READ ALL CSV FILES
# --------------------------------------------------

csv_files = list(folder_path.glob("*.csv"))

seller_data = []

for file in csv_files:

    # IMPORTANT:
    # Don't process the files we create later
    if file.stem.startswith("seller_details_"):
        continue

    cleaned_df = clean_seller_file(file)

    seller_data.append(cleaned_df)


# --------------------------------------------------
# 5. COMBINE ALL FILES
# --------------------------------------------------

Seller_Table = pd.concat(
    seller_data,
    ignore_index=True
)


# --------------------------------------------------
# 6. FINAL COLUMN ORDER
# --------------------------------------------------

Seller_Table = Seller_Table[
    [
        "sku",
        "marketplace",
        "seller_name",
        "Region",
        "Advertised_Price",
        "Violation_Date"
    ]
]


# --------------------------------------------------
# 7. SPLIT BY REGION
# --------------------------------------------------

regions = ["USA", "UAE", "UK", "IND", "CAN"]

for region in regions:

    region_df = Seller_Table[
        Seller_Table["Region"].str.upper() == region
    ].copy()

    output_file = folder_path / f"seller_details_{region}.csv"

    region_df.to_csv(
        output_file,
        index=False
    )


# --------------------------------------------------
# 8. DISPLAY RESULTS
# --------------------------------------------------

print("Processing completed successfully.")

print("\nTotal records:", len(Seller_Table))

print("\nRecords by region:")
print(Seller_Table["Region"].value_counts())

print("\nFiles saved in:")
print(folder_path)

Processing completed successfully.

Total records: 19720

Records by region:
Region
CAN    4100
UAE    3984
USA    3928
IND    3866
UK     3842
Name: count, dtype: Int64

Files saved in:
C:\Data Science\MAP Project\Seller Files

In [174]:
Seller_Table = pd.read_csv("C:/Data Science/MAP Project/Seller Files/seller_details_IND.csv")

In [181]:
Seller_Table_cleaned = Seller_Table.copy()

In [176]:
Seller_Table["sku"] = Seller_Table["sku"].astype("string").str.strip()
Seller_Table["marketplace"] = Seller_Table["marketplace"].astype("string").str.strip()
Seller_Table["seller_name"] = Seller_Table["seller_name"].astype("string").str.strip()
Seller_Table["Region"] = Seller_Table["Region"].astype("string").str.strip()
Seller_Table["Advertised_Price"] = Seller_Table["Advertised_Price"].astype("int")
Seller_Table["Violation_Date"] = pd.to_datetime(Seller_Table["Violation_Date"],errors="coerce")

Seller_Table = Seller_Table.rename(columns={"sku" : "SKU", "marketplace" : "Marketplace", "seller_name" : "Seller_Name"})

In [178]:
Seller_Table.to_excel(r"C:\Data Science\MAP Project\Cleaned files\Seller_Table_cleaned.xlsx",index=False)

## 2.h. Price Monitoring Table

In [246]:
Price_Monitoring_Table = Seller_Table_cleaned.copy()

In [247]:
Price_Monitoring_Table.isna().sum()

SKU                 0
Marketplace         0
Seller_Name         0
Region              0
Advertised_Price    0
Violation_Date      0
dtype: int64

In [248]:
Price_Monitoring_Table = Price_Monitoring_Table.merge(
                                                Price_List_Table_cleaned[["SKU", "MAP", "LPP_Price"]],
                                                on=["SKU"],
                                                how="left")

In [249]:
Price_Monitoring_Table = Price_Monitoring_Table.merge(
                                                Category_Mapping_Table_cleaned[["SKU", "Sub Category"]],
                                                on=["SKU"],
                                                how="left")

In [250]:
Price_Monitoring_Table = Price_Monitoring_Table.merge(
                                                Promotion_Table_cleaned[["SKU", "Season", "Promotion"]],
                                                on=["SKU"],
                                                how="left")

In [251]:
Price_Monitoring_Table = Price_Monitoring_Table.rename(columns={"Seller_Name" : "Advertised Seller Name"})

In [252]:
Price_Monitoring_Table = Price_Monitoring_Table.merge(
                                                Seller_Mapping_Table_cleaned[["Advertised Seller Name", "Actual Seller"]],
                                                on=["Advertised Seller Name"],
                                                how="left")

In [253]:
Price_Monitoring_Table.to_csv(
    r"C:/Data Science/MAP Project/Cleaned files/Price_Monitoring_Table.csv",
    index=False
)

In [257]:
Price_Monitoring_Table["MAP"].isna().sum()

np.int64(0)

In [190]:
from pathlib import Path

folder_path = Path(r"Data Science/MAP Project/Seller Files")

csv_files = list(folder_path.glob("*.csv"))

print(csv_files)
print("Number of files:", len(csv_files))

[]
Number of files: 0

In [255]:
Price_Monitoring_Table = Price_Monitoring_Table[
    Price_Monitoring_Table["MAP"].notna()
]

In [256]:
Price_Monitoring_Table.head(50)

,SKU,Marketplace,Advertised Seller Name,Region,Advertised_Price,Violation_Date,MAP,LPP_Price,Sub Category,Season,Promotion,Actual Seller
0,64V81AA,Snapdeal,MAHIN ENTERPRISE Point,IND,8630,2025-12-21,7629.0,7537.0,Monitor,Q4,0.0,Piggly Wiggly
1,3JA77AA,eBay,Avenue Overseas Private Limited,IND,2247,2025-12-21,2310.0,2159.0,Ink,Q4,0.0,True Value Co.
2,W2093A,Amazon,Lucky Kart,IND,5590,2025-12-21,4906.0,4459.0,Toner,Q4,0.0,CVS Health Corporation
3,715A4A,Snapdeal,Matural,IND,20590,2025-12-21,18059.0,16885.0,Laser Jet,Q4,0.0,H.E. Butt Grocery
4,588L3D,Amazon,supreme Deals,IND,5260,2025-12-21,4610.0,4554.0,Ink Jet,Q4,0.0,Shell Oil Company
5,7W474PA,Amazon,Walvia,IND,43830,2025-12-21,39846.0,38491.0,Laptop,Q4,0.0,Petco
6,2Z615A,Snapdeal,NOBEL HYGIENE PVT. LTD.,IND,30380,2025-12-21,27869.0,26057.0,Laser Jet,Q4,0.0,O'Reilly Auto Parts
7,7S4N7PA,eBay,Casecandy,IND,74090,2025-12-21,70559.0,68159.0,Laptop,Q4,0.0,Chewy.com
8,C2P20AA,Amazon,IFIHomes,IND,1780,2025-12-21,1636.0,1529.0,Ink,Q4,0.0,Meijer
9,4K5D5PA,Flipkart,MANGUKIYA EMPIRE,IND,40170,2025-12-21,37199.0,35934.0,Laptop,Q4,0.0,AT&T Wireless
10,8F6D3PA,eBay,omenterprise11,IND,137790,2025-12-21,121939.0,117793.0,Laptop,Q4,0.0,Sherwin-Williams
11,Q2612AF,eBay,Onsite Electro Services Private Limited,IND,16540,2025-12-21,14901.0,13545.0,Toner,Q4,0.0,Foot Locker
12,588J8B,Amazon,amiciKart,IND,6590,2025-12-21,6044.0,5971.0,Ink Jet,Q4,0.0,O'Reilly Auto Parts
13,8C4R6PA,Snapdeal,NISHIV,IND,152892,2025-12-21,128699.0,124323.0,Laptop,Q4,0.0,Macy's
14,CN634A,Amazon,FABTEC,IND,9930,2025-12-21,8946.0,8364.0,Ink,Q4,0.0,AVB Brandsource
15,CN693AA,eBay,HighSpark™,IND,1010,2025-12-21,914.0,854.0,Ink,Q4,0.0,Academy Sports
16,W2042A,Amazon,iBELL,IND,12330,2025-12-21,11008.0,10006.0,Toner,Q4,0.0,Walgreens Boots Alliance
17,CF287A,Amazon,More HM Sahakarnagar,IND,25350,2025-12-21,24143.0,21945.0,Toner,Q4,0.0,Staples
18,X4E75AA,eBay,Mangalam & CamPure,IND,1260,2025-12-21,1186.0,1108.0,Ink,Q4,0.0,Raley's Supermarkets
19,CF502A,eBay,V Guard Industries Ltd(Official),IND,8840,2025-12-21,8112.0,7373.0,Toner,Q4,0.0,Verizon Wireless
20,7M654PA,Amazon,Emarat Impex,IND,57760,2025-12-21,52509.0,50723.0,Laptop,Q4,0.0,Wegmans Food Market
21,CF362X,eBay,NETBOON,IND,37150,2025-12-21,33770.0,30696.0,Toner,Q4,0.0,Burlington
22,8C527PA,Snapdeal,Mintree Premier Lifestyle,IND,102250,2025-12-21,92119.0,88986.0,Laptop,Q4,0.0,Defense Commissary Agency
23,F9K03A,Snapdeal,Frootle India Pvt. Ltd.,IND,11110,2025-12-21,10009.0,9358.0,Ink,Q4,0.0,Target
24,7Y6U2PA,Flipkart,MiEstilo,IND,109670,2025-12-21,148199.0,143160.0,Laptop,Q4,0.0,Lowe's Companies
25,8L147PA,Amazon,Spigen India,IND,296570,2025-12-21,272087.0,262836.0,Laptop,Q4,0.0,WinCo Foods
26,C9458A,eBay,Krishna Homes,IND,7290,2025-12-21,6506.0,6083.0,Ink,Q4,0.0,Raley's Supermarkets
27,8F6K1PA,Flipkart,ONPOINTZ,IND,187910,2025-12-21,169289.0,163533.0,Laptop,Q4,0.0,Casey's General Store
28,7P6Z8PA,Amazon,INDIA MISSION,IND,44760,2025-12-21,41829.0,40406.0,Laptop,Q4,0.0,AutoZone
29,7PS82A,Snapdeal,COKOEYE ®,IND,158300,2025-12-21,138860.0,129834.0,Laser Jet,Q4,0.0,Neiman Marcus
30,498N5A,Snapdeal,TechEzy,IND,6500,2025-12-21,5706.0,5335.0,Ink,Q4,0.0,Barnes and Noble Booksellers
31,F9A28E,Amazon,Lets _Read,IND,171700,2025-12-21,157520.0,155629.0,Ink Jet,Q4,0.0,Ingles
32,CN626AA,eBay,Molnlycke Healthcare India Pvt Ltd,IND,12000,2025-12-21,11427.0,10684.0,Ink,Q4,0.0,Ikea North American Svcs
33,780A7PA,Snapdeal,Bestbuybook,IND,72900,2025-12-21,62309.0,56638.0,Desktop,Q4,0.0,Sprouts Farmers Market
34,C2P26AA,eBay,ALROZA,IND,2378,2025-12-21,2278.0,2129.0,Ink,Q4,0.0,My Demoulas
35,4K0V9PA,Snapdeal,MAA ENTERPRISE-1,IND,2110,2025-12-21,1995.0,1865.0,Ink,Q4,0.0,Dillard's
36,381U2A,Amazon,SHAYONAM®,IND,24560,2025-12-21,21359.0,19970.0,Laser Jet,Q4,0.0,Chedraui
37,95S69PA,Snapdeal,Spigen India,IND,49010,2025-12-21,79049.0,76361.0,Laptop,Q4,0.0,WinCo Foods
38,1PV87A,Snapdeal,VIMAL CLOTHING,IND,79590,2025-12-21,69815.0,65277.0,Laser Jet,Q4,0.0,My Demoulas
39,743A1PA,Snapdeal,PURE-ELEGANCE,IND,27560,2025-12-21,25519.0,24651.0,Laptop,Q4,0.0,PetSmart
40,65P59A6,Snapdeal,Mosaic Wellness Private Ltd.,IND,5780,2025-12-21,8264.0,8164.0,Monitor,Q4,0.0,Walmart
41,8U1H3PA,Flipkart,KHEVNA ENTERPRISE,IND,33730,2025-12-21,51110.0,49372.0,Laptop,Q4,0.0,Lululemon
42,7G6H1PA,Flipkart,Bahucharaji Creation,IND,37170,2025-12-21,33795.0,32645.0,Laptop,Q4,0.0,Big Lots
43,3YP17AA,eBay,Blumaple,IND,3500,2025-12-21,3069.0,2869.0,Ink,Q4,0.0,The Home Depot
44,Z7Y85A,Snapdeal,OBSYDIUM,IND,8570,2025-12-21,7450.0,6772.0,Toner,Q4,0.0,Royal Ahold Delhaize USA
45,64V81AA,eBay,Keli®,IND,8560,2025-12-21,7629.0,7537.0,Monitor,Q4,0.0,Victoria's Secret
46,CE321A,eBay,Yellow Weaves,IND,8130,2025-12-21,7325.0,6658.0,Toner,Q4,0.0,Stater Bros Holdings
47,A00PNPA,Amazon,WINSTAR Online Store(100% CUSTOMER SATISFACTION),IND,102350,2025-12-21,88999.0,85973.0,Laptop,Q4,0.0,Harbor Freight Tools
49,P2V27A,Flipkart,LEOPAX,IND,9251,2025-12-21,8856.0,8280.0,Ink,Q4,1771.0,Lululemon
50,CF402A,Snapdeal,ISEE 360,IND,9880,2025-12-21,8980.0,8162.0,Toner,Q4,0.0,My Demoulas

In [208]:
Price_Monitoring_Table.columns

Index(['SKU', 'Marketplace', 'Advertised Seller Name', 'Region',
       'Advertised_Price', 'Violation_Date', 'MAP', 'LPP_Price',
       'Sub Category', 'Season', 'Promotion', 'Actual Seller'],
      dtype='str')

# 3. Violation table logic

## Create VIOLATION Table

In [258]:
import pandas as pd
import numpy as np

# Select the required columns for the Violation Table
columns = [
    "SKU",
    "Marketplace",
    "Advertised Seller Name",
    "Region",
    "Violation_Date",
    "Sub Category",
    "Actual Seller"
]

Violation_Table = Price_Monitoring_Table[columns].copy()

# Add pricing fields temporarily for calculating violations
Violation_Table["Advertised Price"] = pd.to_numeric(
    Price_Monitoring_Table["Advertised_Price"], errors="coerce"
)
Violation_Table["MAP"] = pd.to_numeric(
    Price_Monitoring_Table["MAP"], errors="coerce"
)
Violation_Table["LPP_Price"] = pd.to_numeric(
    Price_Monitoring_Table["LPP_Price"], errors="coerce"
)
Violation_Table["Promotion"] = pd.to_numeric(
    Price_Monitoring_Table["Promotion"], errors="coerce"
)

# Calculate the promotional allowed limit
Violation_Table["Allowed_Limit"] = (
    Violation_Table["MAP"] - Violation_Table["Promotion"]
)

# Initialize the three policy columns
Violation_Table["Policy Compliant"] = "NO"
Violation_Table["Promotion Violation"] = "NO"
Violation_Table["LPP Violation"] = "NO"

# Validate required pricing data before classification
required = ["Advertised Price", "MAP", "LPP_Price", "Promotion"]

if Violation_Table[required].isna().any().any():
    raise ValueError(
        "Missing or invalid price data found. "
        "Please clean the affected rows before continuing."
    )

# Rule 1: Advertised price is at or above MAP
mask = Violation_Table["Advertised Price"] >= Violation_Table["MAP"]
Violation_Table.loc[mask, "Policy Compliant"] = "YES"

# Rule 2: Promotion exists and price is within the allowed limit
mask = (
    (Violation_Table["Promotion"] > 0) &
    (Violation_Table["Advertised Price"] < Violation_Table["MAP"]) &
    (Violation_Table["Advertised Price"] >= Violation_Table["Allowed_Limit"])
)
Violation_Table.loc[mask, "Policy Compliant"] = "YES"

# Rule 3: Promotion exists and price is below allowed limit,
# but is not below LPP
mask = (
    (Violation_Table["Promotion"] > 0) &
    (Violation_Table["Advertised Price"] < Violation_Table["Allowed_Limit"]) &
    (Violation_Table["Advertised Price"] >= Violation_Table["LPP_Price"])
)
Violation_Table.loc[mask, "Promotion Violation"] = "YES"

# Rule 4: Promotion exists and price is below both limits
mask = (
    (Violation_Table["Promotion"] > 0) &
    (Violation_Table["Advertised Price"] < Violation_Table["Allowed_Limit"]) &
    (Violation_Table["Advertised Price"] < Violation_Table["LPP_Price"])
)
Violation_Table.loc[mask, "Promotion Violation"] = "YES"
Violation_Table.loc[mask, "LPP Violation"] = "YES"

# Rule 5: No promotion, but price is below MAP and at/above LPP
mask = (
    (Violation_Table["Promotion"] == 0) &
    (Violation_Table["Advertised Price"] < Violation_Table["MAP"]) &
    (Violation_Table["Advertised Price"] >= Violation_Table["LPP_Price"])
)
Violation_Table.loc[mask, "Policy Compliant"] = "YES"

# Rule 6: No promotion and price is below LPP
mask = (
    (Violation_Table["Promotion"] == 0) &
    (Violation_Table["Advertised Price"] < Violation_Table["LPP_Price"])
)
Violation_Table.loc[mask, "LPP Violation"] = "YES"

# Check the result
display(Violation_Table.head(10))

,SKU,Marketplace,Advertised Seller Name,Region,Violation_Date,Sub Category,Actual Seller,Advertised Price,MAP,LPP_Price,Promotion,Allowed_Limit,Policy Compliant,Promotion Violation,LPP Violation
0,64V81AA,Snapdeal,MAHIN ENTERPRISE Point,IND,2025-12-21,Monitor,Piggly Wiggly,8630,7629.0,7537.0,0.0,7629.0,YES,NO,NO
1,3JA77AA,eBay,Avenue Overseas Private Limited,IND,2025-12-21,Ink,True Value Co.,2247,2310.0,2159.0,0.0,2310.0,YES,NO,NO
2,W2093A,Amazon,Lucky Kart,IND,2025-12-21,Toner,CVS Health Corporation,5590,4906.0,4459.0,0.0,4906.0,YES,NO,NO
3,715A4A,Snapdeal,Matural,IND,2025-12-21,Laser Jet,H.E. Butt Grocery,20590,18059.0,16885.0,0.0,18059.0,YES,NO,NO
4,588L3D,Amazon,supreme Deals,IND,2025-12-21,Ink Jet,Shell Oil Company,5260,4610.0,4554.0,0.0,4610.0,YES,NO,NO
5,7W474PA,Amazon,Walvia,IND,2025-12-21,Laptop,Petco,43830,39846.0,38491.0,0.0,39846.0,YES,NO,NO
6,2Z615A,Snapdeal,NOBEL HYGIENE PVT. LTD.,IND,2025-12-21,Laser Jet,O'Reilly Auto Parts,30380,27869.0,26057.0,0.0,27869.0,YES,NO,NO
7,7S4N7PA,eBay,Casecandy,IND,2025-12-21,Laptop,Chewy.com,74090,70559.0,68159.0,0.0,70559.0,YES,NO,NO
8,C2P20AA,Amazon,IFIHomes,IND,2025-12-21,Ink,Meijer,1780,1636.0,1529.0,0.0,1636.0,YES,NO,NO
9,4K5D5PA,Flipkart,MANGUKIYA EMPIRE,IND,2025-12-21,Laptop,AT&T Wireless,40170,37199.0,35934.0,0.0,37199.0,YES,NO,NO

## Data analysis in violation table

In [259]:
# Count Promotion Violations
promotion_count = (
    Violation_Table["Promotion Violation"] == "YES"
).sum()

# Count LPP Violations
lpp_count = (
    Violation_Table["LPP Violation"] == "YES"
).sum()

print("Total Promotion Violations:", promotion_count)
print("Total LPP Violations:", lpp_count)

Total Promotion Violations: 16
Total LPP Violations: 387

In [260]:
Repeated_SKU_Table = Violation_Table[
    Violation_Table.duplicated(
        subset=["Actual Seller", "SKU"],
        keep=False
    )
].sort_values(
    ["Actual Seller", "SKU", "Violation_Date"]
).reset_index(drop=True)

display(Repeated_SKU_Table)

,SKU,Marketplace,Advertised Seller Name,Region,Violation_Date,Sub Category,Actual Seller,Advertised Price,MAP,LPP_Price,Promotion,Allowed_Limit,Policy Compliant,Promotion Violation,LPP Violation
0,1F3W3A,Snapdeal,ELEMENT ENTERPRISES,IND,2025-12-21,Ink Jet,7-Eleven,7310,10441.0,10315.0,0.0,10441.0,NO,NO,YES
1,1F3W3A,Snapdeal,ELEMENT ENTERPRISES,IND,2025-12-22,Ink Jet,7-Eleven,7310,10441.0,10315.0,0.0,10441.0,NO,NO,YES
2,2RM82A,Snapdeal,The Old Natural,IND,2025-12-21,Ink Jet,7-Eleven,1181740,1074306.0,1061414.0,0.0,1074306.0,YES,NO,NO
3,2RM82A,Snapdeal,The Old Natural,IND,2025-12-22,Ink Jet,7-Eleven,1181740,1074306.0,1061414.0,0.0,1074306.0,YES,NO,NO
4,3YM16AA,eBay,Dingger,IND,2025-12-21,Ink,7-Eleven,1250,1130.0,1056.0,0.0,1130.0,YES,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3745,CZ184A,Amazon,Farm Naturelle,IND,2025-12-22,Laser Jet,WinCo Foods,29080,25283.0,23639.0,0.0,25283.0,YES,NO,NO
3746,L0S51AA,Snapdeal,ARLICORPING,IND,2025-12-21,Ink,WinCo Foods,2240,1986.0,1856.0,0.0,1986.0,YES,NO,NO
3747,L0S51AA,Snapdeal,ARLICORPING,IND,2025-12-22,Ink,WinCo Foods,2240,1986.0,1856.0,0.0,1986.0,YES,NO,NO
3748,Z7Y68A,Flipkart,Spigen India,IND,2025-12-21,Toner,WinCo Foods,8040,7376.0,6704.0,0.0,7376.0,YES,NO,NO
3749,Z7Y68A,Flipkart,Spigen India,IND,2025-12-22,Toner,WinCo Foods,8040,7376.0,6704.0,0.0,7376.0,YES,NO,NO

In [261]:
Reseller_SKU_Count = (
    Violation_Table
    .groupby(["Actual Seller", "SKU"])
    .size()
    .reset_index(name="Observation Count")
    .query("`Observation Count` > 1")
    .sort_values(
        ["Observation Count", "Actual Seller"],
        ascending=[False, True]
    )
    .reset_index(drop=True)
)

display(Reseller_SKU_Count)

         Actual Seller      SKU  Observation Count
0       Academy Sports   CF256A                  4
1         Advance Auto  9W6U6PA                  4
2               Kohl's  8L130PA                  4
3               Kohl's  9U7H2PA                  4
4     Lowe's Companies   CF362X                  4
...                ...      ...                ...
1858       WinCo Foods   CF214A                  2
1859       WinCo Foods   CF380A                  2
1860       WinCo Foods   CZ184A                  2
1861       WinCo Foods  L0S51AA                  2
1862       WinCo Foods   Z7Y68A                  2

[1863 rows x 3 columns]

In [270]:
Violation_Table[Violation_Table["Promotion Violation"] == "YES"]

,SKU,Marketplace,Advertised Seller Name,Region,Violation_Date,Sub Category,Actual Seller,Advertised Price,MAP,LPP_Price,Promotion,Allowed_Limit,Policy Compliant,Promotion Violation,LPP Violation,Promotion Violation Count,LPP Violation Count,Recommended Action
484,P2V64A,eBay,Gesto®,IND,2025-12-21,Ink,O'Reilly Auto Parts,3650,5788.0,5411.0,1157.0,4631.0,NO,YES,YES,1,1,Warning Letter
568,P2V27A,Snapdeal,Organic Products Inc,IND,2025-12-21,Ink,Dillard's,6110,8856.0,8280.0,1771.0,7085.0,NO,YES,YES,1,1,Warning Letter
1198,L0S60AA,Snapdeal,Quality Desk,IND,2025-12-21,Ink,Wakefern / ShopRite,1700,2786.0,2604.0,557.0,2229.0,NO,YES,YES,1,1,Warning Letter
1252,8L145PA,Snapdeal,Opulent Products,IND,2025-12-21,Laptop,Gap,113660,160079.0,154636.0,24011.0,136068.0,NO,YES,YES,1,1,Warning Letter
1850,7K667PA,Snapdeal,Moxie Beauty,IND,2025-12-21,Desktop,True Value Co.,58170,79679.0,72428.0,11951.0,67728.0,NO,YES,YES,1,1,Warning Letter
2090,805X2PA,eBay,PRAGUDO®,IND,2025-12-22,Laptop,Giant Eagle,38792,67343.0,65053.0,10101.0,57242.0,NO,YES,YES,1,1,Warning Letter
2238,8L146PA,Amazon,MEXPONE,IND,2025-12-22,Laptop,J.C. Penney Company,126504,232544.0,224637.0,34881.0,197663.0,NO,YES,YES,1,1,Warning Letter
2549,P2V64A,eBay,Gesto®,IND,2025-12-22,Ink,O'Reilly Auto Parts,3650,5788.0,5411.0,1157.0,4631.0,NO,YES,YES,2,2,Warning Letter
2603,8L145PA,Snapdeal,Opulent Products,IND,2025-12-22,Laptop,Gap,113660,160079.0,154636.0,24011.0,136068.0,NO,YES,YES,2,2,Warning Letter
2617,87G01PA,Flipkart,Book Universe 2021,IND,2025-12-22,Desktop,Health Mart Systems,50080,84599.0,76900.0,12689.0,71910.0,NO,YES,YES,1,1,Warning Letter
2649,3WX00A,Snapdeal,Kalptaru Trades.,IND,2025-12-22,Ink,True Value Co.,2256,2893.0,2704.0,578.0,2315.0,NO,YES,YES,1,1,Warning Letter
2774,90N54PA,Amazon,ZCARE.PHARMA,IND,2025-12-22,Laptop,Verizon Wireless,57328,106949.0,103312.0,16042.0,90907.0,NO,YES,YES,1,1,Warning Letter
3296,P2V27A,Snapdeal,Organic Products Inc,IND,2025-12-22,Ink,Dillard's,6110,8856.0,8280.0,1771.0,7085.0,NO,YES,YES,2,2,Warning Letter
3393,90N54PA,Snapdeal,KHADI MAURI HERBAL,IND,2025-12-22,Laptop,Amway,63312,106949.0,103312.0,16042.0,90907.0,NO,YES,YES,1,1,Warning Letter
3408,L0S60AA,Snapdeal,Quality Desk,IND,2025-12-22,Ink,Wakefern / ShopRite,1700,2786.0,2604.0,557.0,2229.0,NO,YES,YES,2,2,Warning Letter
3595,7K667PA,Snapdeal,Moxie Beauty,IND,2025-12-22,Desktop,True Value Co.,58170,79679.0,72428.0,11951.0,67728.0,NO,YES,YES,2,2,Warning Letter

## ADD counter to track the repeated violation

In [264]:
# Convert violation dates to datetime
Violation_Table["Violation_Date"] = pd.to_datetime(
    Violation_Table["Violation_Date"],
    errors="coerce"
)

# Sort chronologically
Violation_Table = Violation_Table.sort_values(
    ["Violation_Date"],
    kind="stable",
    na_position="last"
).reset_index(drop=True)

# Count promotion violations independently
Violation_Table["Promotion Violation Count"] = (
    Violation_Table.groupby(
        ["Actual Seller", "SKU"]
    )["Promotion Violation"]
    .transform(lambda s: s.eq("YES").cumsum())
)

# Count LPP violations independently
Violation_Table["LPP Violation Count"] = (
    Violation_Table.groupby(
        ["Actual Seller", "SKU"]
    )["LPP Violation"]
    .transform(lambda s: s.eq("YES").cumsum())
)

# Determine the action for each observation
Violation_Table["Recommended Action"] = "No Action"

violation_mask = (
    (Violation_Table["Promotion Violation"] == "YES") |
    (Violation_Table["LPP Violation"] == "YES")
)

suspension_mask = (
    (Violation_Table["Promotion Violation Count"] >= 3) |
    (Violation_Table["LPP Violation Count"] >= 3)
)

Violation_Table.loc[violation_mask, "Recommended Action"] = (
    "Warning Letter"
)

Violation_Table.loc[suspension_mask & violation_mask,
                    "Recommended Action"] = "SKU Suspension Letter"

display(Violation_Table.head(5))

,SKU,Marketplace,Advertised Seller Name,Region,Violation_Date,Sub Category,Actual Seller,Advertised Price,MAP,LPP_Price,Promotion,Allowed_Limit,Policy Compliant,Promotion Violation,LPP Violation,Promotion Violation Count,LPP Violation Count,Recommended Action
0,64V81AA,Snapdeal,MAHIN ENTERPRISE Point,IND,2025-12-21,Monitor,Piggly Wiggly,8630,7629.0,7537.0,0.0,7629.0,YES,NO,NO,0,0,No Action
1,3JA77AA,eBay,Avenue Overseas Private Limited,IND,2025-12-21,Ink,True Value Co.,2247,2310.0,2159.0,0.0,2310.0,YES,NO,NO,0,0,No Action
2,W2093A,Amazon,Lucky Kart,IND,2025-12-21,Toner,CVS Health Corporation,5590,4906.0,4459.0,0.0,4906.0,YES,NO,NO,0,0,No Action
3,715A4A,Snapdeal,Matural,IND,2025-12-21,Laser Jet,H.E. Butt Grocery,20590,18059.0,16885.0,0.0,18059.0,YES,NO,NO,0,0,No Action
4,588L3D,Amazon,supreme Deals,IND,2025-12-21,Ink Jet,Shell Oil Company,5260,4610.0,4554.0,0.0,4610.0,YES,NO,NO,0,0,No Action

## Generate the violation warning and suspension letters

In [266]:
%pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: lxml>=3.1.0 in C:\Users\varun\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-docx) (6.1.3)
Requirement already satisfied: typing_extensions>=4.9.0 in C:\Users\varun\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-docx) (4.15.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
Installing collected packages: python-docx
Successfully installed python-docx-1.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [269]:
import pandas as pd
from docx import Document
from docx.shared import Inches, Pt
from pathlib import Path
import re

# Manufacturer name
MANUFACTURER = "Manufacturing Company"

# Output folder
output_folder = Path(
    "C:/Data Science/MAP Project/MAP Violation letters"
)
output_folder.mkdir(parents=True, exist_ok=True)

letters_created = 0
warning_count = 0
suspension_count = 0

# Helper function to handle missing values
def clean_value(value):
    if pd.isna(value):
        return "Not available"
    return str(value).strip()


# Select observations with a pricing violation
letters = Violation_Table[
    (
        pd.to_numeric(
            Violation_Table["LPP Violation Count"],
            errors="coerce"
        ).fillna(0) > 0
    )
    |
    (
        pd.to_numeric(
            Violation_Table["Promotion Violation Count"],
            errors="coerce"
        ).fillna(0) > 0
    )
].copy()


# Generate one separate Word document per observation
for observation_number, (_, row) in enumerate(
    letters.iterrows(), start=1
):

    # Read violation counts
    lpp_count = pd.to_numeric(
        pd.Series([row["LPP Violation Count"]]),
        errors="coerce"
    ).fillna(0).iloc[0]

    promotion_count = pd.to_numeric(
        pd.Series([row["Promotion Violation Count"]]),
        errors="coerce"
    ).fillna(0).iloc[0]

    # Determine violation type
    violation_types = []

    if lpp_count > 0:
        violation_types.append("MAP Violation")

    if promotion_count > 0:
        violation_types.append("Promotion Violation")

    violation_type = " and ".join(violation_types)

    # More than 3 violations of either type triggers suspension
    if lpp_count > 3 or promotion_count > 3:
        action = "Suspension"
        title = "SKU SUSPENSION NOTICE"
        subject = (
            f"SKU Suspension Notice - {violation_type}"
        )
        suspension_count += 1

    else:
        action = "Warning"
        title = "WARNING NOTICE - PRICING POLICY VIOLATION"
        subject = (
            f"Warning Notice - {violation_type}"
        )
        warning_count += 1

    # Create a NEW Word document for this observation
    doc = Document()

    # Page margins and default font
    section = doc.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)

    doc.styles["Normal"].font.name = "Arial"
    doc.styles["Normal"].font.size = Pt(10)

    # Basic information
    sku = clean_value(row["SKU"])
    actual_seller = clean_value(row["Actual Seller"])

    violation_date = row["Violation_Date"]

    if pd.notna(violation_date):
        date_text = pd.to_datetime(
            violation_date
        ).strftime("%B %d, %Y")
    else:
        date_text = "Date unavailable"

    # Letter heading
    doc.add_heading(MANUFACTURER, level=1)
    doc.add_paragraph(f"From: {MANUFACTURER}")
    doc.add_paragraph(f"To: {actual_seller}")
    doc.add_paragraph(f"Date: {date_text}")

    doc.add_heading(title, level=2)
    doc.add_paragraph(f"Subject: {subject}")

    # Violation details
    doc.add_heading("Violation Details", level=3)

    details = [
        ("SKU", sku),
        ("Violation Type", violation_type),
        ("Recommended Action", action),
        ("Marketplace", clean_value(row["Marketplace"])),
        (
            "Advertised Seller Name",
            clean_value(row["Advertised Seller Name"])
        ),
        ("Actual Seller", actual_seller),
        ("Region", clean_value(row["Region"])),
        ("Violation Date", date_text),
        ("Sub Category", clean_value(row["Sub Category"])),
        ("LPP Violation Count", int(lpp_count)),
        ("Promotion Violation Count", int(promotion_count)),
    ]

    table = doc.add_table(rows=0, cols=2)
    table.style = "Table Grid"

    for label, value in details:
        cells = table.add_row().cells
        cells[0].text = label
        cells[1].text = str(value)

    doc.add_paragraph()
    doc.add_paragraph("Dear Reseller,")

    # Letter content based on action
    if action == "Warning":

        if lpp_count > 0 and promotion_count > 0:
            message = (
                f"Our records indicate that SKU {sku} has "
                "pricing violations relating to both the "
                "applicable MAP policy and "
                "promotional pricing requirements. Please "
                "review the applicable pricing requirements "
                "and correct the advertised price as necessary."
            )

        elif lpp_count > 0:
            message = (
                f"Our records indicate that the advertised "
                f"price for SKU {sku} is below the applicable "
                "Lowest Permitted Price (LPP), constituting "
                "a MAP policy violation under the applicable "
                "pricing rules. Please correct the advertised "
                "price and ensure future compliance."
            )

        else:
            message = (
                f"Our records indicate that the advertised "
                f"price for SKU {sku} does not comply with "
                "the applicable promotional pricing "
                "requirements. Please review the applicable "
                "promotion and correct the advertised price "
                "as necessary."
            )

        doc.add_paragraph(message)

        doc.add_paragraph(
            "This notice serves as a warning. Please take "
            "the required corrective action and ensure "
            "future compliance with the applicable "
            "manufacturer pricing policies."
        )

    else:
        # Suspension notice
        reasons = []

        if lpp_count > 3:
            reasons.append(
                f"more than three LPP-related violations "
                f"({int(lpp_count)} recorded)"
            )

        if promotion_count > 3:
            reasons.append(
                f"more than three promotion violations "
                f"({int(promotion_count)} recorded)"
            )

        reason_text = " and ".join(reasons)

        doc.add_paragraph(
            f"Repeated pricing violations have been recorded "
            f"for SKU {sku}. The recorded violation history "
            f"meets the suspension threshold: {reason_text}."
        )

        doc.add_paragraph(
            f"You are hereby notified that selling rights for "
            f"SKU {sku} are subject to suspension in accordance "
            "with the applicable manufacturer agreement and "
            "enforcement process. Please discontinue selling "
            "this specific SKU as directed by the manufacturer "
            "under the applicable agreement."
        )

        doc.add_paragraph(
            "This notice applies only to the identified SKU. "
            "Other products from the manufacturer may continue "
            "to be sold in accordance with the applicable "
            "agreement and pricing policies."
        )

    doc.add_paragraph(
        "Please review the applicable manufacturer pricing "
        "policy and take the required corrective action."
    )

    doc.add_paragraph("Sincerely,")
    doc.add_paragraph(
        f"Compliance Team\n{MANUFACTURER}"
    )

    # Create a unique filename for every observation
    safe_seller = re.sub(
        r'[<>:"/\\\\|?*]', "_", actual_seller
    )
    safe_sku = re.sub(
        r'[<>:"/\\\\|?*]', "_", sku
    )

    output_file = output_folder / (
        f"Notice_{observation_number:04d}_"
        f"{safe_seller}_{safe_sku}.docx"
    )

    # Save this individual document immediately
    doc.save(output_file)
    letters_created += 1

    print(f"Saved: {output_file.name}")


# Final summary
print("\nLetter generation completed.")
print(f"Total individual letters created: {letters_created}")
print(f"Warning letters: {warning_count}")
print(f"Suspension letters: {suspension_count}")
print(f"Output folder: {output_folder.resolve()}")

Saved: Notice_0001_Lowe's Companies_7Y6U2PA.docx
Saved: Notice_0002_WinCo Foods_95S69PA.docx
Saved: Notice_0003_Walmart_65P59A6.docx
Saved: Notice_0004_Lululemon_8U1H3PA.docx
Saved: Notice_0005_Tractor Supply Co._C2P23AA.docx
Saved: Notice_0006_Academy Sports_CF256A.docx
Saved: Notice_0007_J.C. Penney Company_6K7U2PA.docx
Saved: Notice_0008_Signet Jewelers_W1580A.docx
Saved: Notice_0009_Good Neighbor Pharmacy_72K10PA.docx
Saved: Notice_0010_Hobby Lobby Stores_CE401A.docx
Saved: Notice_0011_Victoria's Secret_T6M01AA.docx
Saved: Notice_0012_Lululemon_84H53PA.docx
Saved: Notice_0013_Williams-Sonoma_841W7PA.docx
Saved: Notice_0014_Apple Stores _ iTunes_8L144PA.docx
Saved: Notice_0015_Hy Vee_3ED28A.docx
Saved: Notice_0016_Dillard's_840G6PA.docx
Saved: Notice_0017_Raley's Supermarkets_8X059PA.docx
Saved: Notice_0018_Ulta Beauty_F9J67A.docx
Saved: Notice_0019_Aldi_L0H25A.docx
Saved: Notice_0020_Rite Aid_6PA50A4.docx
Saved: Notice_0021_Dick's Sporting Goods_4J0N0PA.docx
Saved: Notice_0022_Casey's General Store_CZ134A.docx
Saved: Notice_0023_Wayfair_W2091A.docx
Saved: Notice_0024_Royal Ahold Delhaize USA_CZ123AA.docx
Saved: Notice_0025_Discount Tire_CF256X.docx
Saved: Notice_0026_Neiman Marcus_CZ135A.docx
Saved: Notice_0027_J.C. Penney Company_889G9PA.docx
Saved: Notice_0028_Chewy.com_8F6D3PA.docx
Saved: Notice_0029_Chedraui_T6L97AA.docx
Saved: Notice_0030_Piggly Wiggly_8L144PA.docx
Saved: Notice_0031_Academy Sports_832Q8PA.docx
Saved: Notice_0032_Schnucks_F9J77A.docx
Saved: Notice_0033_Health Mart Systems_F9K02A.docx
Saved: Notice_0034_Walgreens Boots Alliance_7Q6Z2PA.docx
Saved: Notice_0035_Health Mart Systems_7KW64A.docx
Saved: Notice_0036_O'Reilly Auto Parts_P2V64A.docx
Saved: Notice_0037_Save-A-Lot_L3U43A.docx
Saved: Notice_0038_Dollar General_F6V20AA.docx
Saved: Notice_0039_Aldi_F9K03A.docx
Saved: Notice_0040_Dillard's_P2V27A.docx
Saved: Notice_0041_Big Lots_3WX01A.docx
Saved: Notice_0042_WinCo Foods_7P704PA.docx
Saved: Notice_0043_CVS Health Corporation_7L033PA.docx
Saved: Notice_0044_Petco_6N030PA.docx
Saved: Notice_0045_PetSmart_7PS84A.docx
Saved: Notice_0046_Shell Oil Company_3G636A.docx
Saved: Notice_0047_True Value Co._9R291PA.docx
Saved: Notice_0048_Qurate Retail_C2P04AA.docx
Saved: Notice_0049_Bath & Body Works_8L149PA.docx
Saved: Notice_0050_The Home Depot_9Y0Z1PA.docx
Saved: Notice_0051_Hy Vee_54R50B.docx
Saved: Notice_0052_Publix Super Markets_81M38AA.docx
Saved: Notice_0053_Total Wine & More_F9K06A.docx
Saved: Notice_0054_Gap_W2111X.docx
Saved: Notice_0055_Ikea North American Svcs_498N6A.docx
Saved: Notice_0056_Sephora (LVMH)_3WX38A.docx
Saved: Notice_0057_Piggly Wiggly_7Y6U1PA.docx
Saved: Notice_0058_Amazon.com_78Y44PA.docx
Saved: Notice_0059_Giant Eagle_W2040A.docx
Saved: Notice_0060_Barnes and Noble Booksellers_L0S69AA.docx
Saved: Notice_0061_The Kroger Co._8F6D5PA.docx
Saved: Notice_0062_Ross Stores_CE285A.docx
Saved: Notice_0063_Qurate Retail_A00PNPA.docx
Saved: Notice_0064_Big Lots_8L149PA.docx
Saved: Notice_0065_Save-A-Lot_8Z7W5PA.docx
Saved: Notice_0066_7-Eleven_1F3W3A.docx
Saved: Notice_0067_Kohl's_9U7H2PA.docx
Saved: Notice_0068_Burlington_CC388X.docx
Saved: Notice_0069_AT&T Wireless_CZ121AA.docx
Saved: Notice_0070_BJ's Wholesale Club_CF513A.docx
Saved: Notice_0071_Defense Commissary Agency_834T9PA.docx
Saved: Notice_0072_Publix Super Markets_A45Y6PA.docx
Saved: Notice_0073_Signet Jewelers_Z7Y69A.docx
Saved: Notice_0074_The Home Depot_CF362X.docx
Saved: Notice_0075_Dollar Tree_9E3K4PA.docx
Saved: Notice_0076_O'Reilly Auto Parts_2Z615A.docx
Saved: Notice_0077_Staples_CZ637AA.docx
Saved: Notice_0078_Chewy.com_W2113A.docx
Saved: Notice_0079_Wakefern _ ShopRite_L0S60AA.docx
Saved: Notice_0080_Dollar General_67V50PA.docx
Saved: Notice_0081_AT&T Wireless_840T7PA.docx
Saved: Notice_0082_Gap_8L145PA.docx
Saved: Notice_0083_CVS Health Corporation_7Q6Z7PA.docx
Saved: Notice_0084_Sprouts Farmers Market_6ZD29AA.docx
Saved: Notice_0085_Hudson's Bay_943S1PA.docx
Saved: Notice_0086_Royal Ahold Delhaize USA_8D667PA.docx
Saved: Notice_0087_Kohl's_8L130PA.docx
Saved: Notice_0088_Dollar General_CN628AA.docx
Saved: Notice_0089_The Kroger Co._9W638PA.docx
Saved: Notice_0090_Academy Sports_CF256A.docx
Saved: Notice_0091_Schnucks_6F967PA.docx
Saved: Notice_0092_Sprouts Farmers Market_P2V62A.docx
Saved: Notice_0093_Gap_T8W18A.docx
Saved: Notice_0094_Target_CH561ZZ.docx
Saved: Notice_0095_Hy Vee_5SE26B.docx
Saved: Notice_0096_Advance Auto_3ED68A.docx
Saved: Notice_0097_Hudson's Bay_84J08PA.docx
Saved: Notice_0098_Amway_2Z614A.docx
Saved: Notice_0099_Alimentation Couche-Tard_840G6PA.docx
Saved: Notice_0100_Walgreens Boots Alliance_4K5D5PA.docx
Saved: Notice_0101_The Home Depot_6C3G1PA.docx
Saved: Notice_0102_Lululemon_28C12A.docx
Saved: Notice_0103_Apple Stores _ iTunes_54R58B.docx
Saved: Notice_0104_Camping World_3JB06AA.docx
Saved: Notice_0105_Staples_7S4N7PA.docx
Saved: Notice_0106_Kohl's_8L130PA.docx
Saved: Notice_0107_The Home Depot_A0EH4PA.docx
Saved: Notice_0108_Alimentation Couche-Tard_W1103A.docx
Saved: Notice_0109_WinCo Foods_95S69PA.docx
Saved: Notice_0110_Williams-Sonoma_40Z26AA.docx
Saved: Notice_0111_Burlington_CF360A.docx
Saved: Notice_0112_Apple Stores _ iTunes_W2303A.docx
Saved: Notice_0113_Qurate Retail_7J180PA.docx
Saved: Notice_0114_Dick's Sporting Goods_7Y6U3PA.docx
Saved: Notice_0115_Amazon.com_7Z481PA.docx
Saved: Notice_0116_Dell Technologies_W2113X.docx
Saved: Notice_0117_Total Wine & More_6N030PA.docx
Saved: Notice_0118_True Value Co._7K667PA.docx
Saved: Notice_0119_Shell Oil Company_CC388A.docx
Saved: Notice_0120_AutoZone_CF359A.docx
Saved: Notice_0121_Wayfair_W2091A.docx
Saved: Notice_0122_Royal Ahold Delhaize USA_CZ123AA.docx
Saved: Notice_0123_Qurate Retail_9Q9M9PA.docx
Saved: Notice_0124_Alimentation Couche-Tard_W1103A.docx
Saved: Notice_0125_Army and Air Force Exchange Service_8C4R6PA.docx
Saved: Notice_0126_The Kroger Co._9W638PA.docx
Saved: Notice_0127_Chewy.com_W2113A.docx
Saved: Notice_0128_Tapestry_F9K15A.docx
Saved: Notice_0129_Health Mart Systems_7KW64A.docx
Saved: Notice_0130_Defense Commissary Agency_834T9PA.docx
Saved: Notice_0131_Ikea North American Svcs_8C4R9PA.docx
Saved: Notice_0132_Kohl's_389A1PA.docx
Saved: Notice_0133_Apple Stores _ iTunes_54R58B.docx
Saved: Notice_0134_Giant Eagle_P2V63A.docx
Saved: Notice_0135_Camping World_3JB06AA.docx
Saved: Notice_0136_Piggly Wiggly_8L144PA.docx
Saved: Notice_0137_Hobby Lobby Stores_CF362X.docx
Saved: Notice_0138_Aldi_F9K03A.docx
Saved: Notice_0139_J.C. Penney Company_5HB10A.docx
Saved: Notice_0140_Sprouts Farmers Market_3JA82AA.docx
Saved: Notice_0141_Bath & Body Works_8L149PA.docx
Saved: Notice_0142_Exxon Mobil Corporation_780A6PA.docx
Saved: Notice_0143_Chewy.com_8F6D3PA.docx
Saved: Notice_0144_Qurate Retail_A00PNPA.docx
Saved: Notice_0145_Schnucks_6F967PA.docx
Saved: Notice_0146_Ulta Beauty_7P6Z8PA.docx
Saved: Notice_0147_Walgreens Boots Alliance_1B9X2AA.docx
Saved: Notice_0148_Michaels Stores_F9J77A.docx
Saved: Notice_0149_Walgreens Boots Alliance_CF232A.docx
Saved: Notice_0150_J.C. Penney Company_6K7U2PA.docx
Saved: Notice_0151_J.C. Penney Company_1F3Y4A.docx
Saved: Notice_0152_Hudson's Bay_3WX26A.docx
Saved: Notice_0153_Advance Auto_3ED68A.docx
Saved: Notice_0154_CVS Health Corporation_CZ131A.docx
Saved: Notice_0155_Signet Jewelers_Z7Y69A.docx
Saved: Notice_0156_Casey's General Store_60K34B.docx
Saved: Notice_0157_The Kroger Co._A46C9PA.docx
Saved: Notice_0158_Giant Eagle_805X2PA.docx
Saved: Notice_0159_WinCo Foods_7P704PA.docx
Saved: Notice_0160_Neiman Marcus_3WX20A.docx
Saved: Notice_0161_Chedraui_9D3N7PA.docx
Saved: Notice_0162_Big Lots_3WX01A.docx
Saved: Notice_0163_Publix Super Markets_3YM71AA.docx
Saved: Notice_0164_Dollar Tree_9E3K4PA.docx
Saved: Notice_0165_Academy Sports_CF256A.docx
Saved: Notice_0166_Burlington_8F8Z5PA.docx
Saved: Notice_0167_Academy Sports_832Q8PA.docx
Saved: Notice_0168_Foot Locker_8L147PA.docx
Saved: Notice_0169_Qurate Retail_7J180PA.docx
Saved: Notice_0170_Stater Bros Holdings_676M8A.docx
Saved: Notice_0171_WinCo Foods_95S69PA.docx
Saved: Notice_0172_Kohl's_W1580X.docx
Saved: Notice_0173_Walgreens Boots Alliance_4K5D5PA.docx
Saved: Notice_0174_Nordstrom_7K5W2PA.docx
Saved: Notice_0175_Chedraui_T6L97AA.docx
Saved: Notice_0176_Target_169L0AA.docx
Saved: Notice_0177_Hy Vee_5SE26B.docx
Saved: Notice_0178_Hudson's Bay_824L6PA.docx
Saved: Notice_0179_WinCo Foods_95S69PA.docx
Saved: Notice_0180_Nordstrom_9Q9M6PA.docx
Saved: Notice_0181_J.C. Penney Company_8L146PA.docx
Saved: Notice_0182_Alimentation Couche-Tard_498N7A.docx
Saved: Notice_0183_Burlington_CF360A.docx
Saved: Notice_0184_Good Neighbor Pharmacy_72K10PA.docx
Saved: Notice_0185_Big Lots_8L149PA.docx
Saved: Notice_0186_Chewy.com_7J4Y1PA.docx
Saved: Notice_0187_Hobby Lobby Stores_CE401A.docx
Saved: Notice_0188_AT&T Wireless_840T7PA.docx
Saved: Notice_0189_Dollar General_67V50PA.docx
Saved: Notice_0190_Walgreens Boots Alliance_7Q6Z2PA.docx
Saved: Notice_0191_Dell Technologies_W2113X.docx
Saved: Notice_0192_Hy Vee_3E7R9PA.docx
Saved: Notice_0193_O'Reilly Auto Parts_CZ638AA.docx
Saved: Notice_0194_Hy Vee_3ED28A.docx
Saved: Notice_0195_Discount Tire_CF256X.docx
Saved: Notice_0196_Dollar General_F6V20AA.docx
Saved: Notice_0197_The Kroger Co._8F6D5PA.docx
Saved: Notice_0198_Publix Super Markets_T6M17AA.docx
Saved: Notice_0199_Dollar Tree_CB542A.docx
Saved: Notice_0200_Dick's Sporting Goods_7K3W9AA.docx
Saved: Notice_0201_Menards_3WX13A.docx
Saved: Notice_0202_Tapestry_3JA82AA.docx
Saved: Notice_0203_Amazon.com_78Y44PA.docx
Saved: Notice_0204_Barnes and Noble Booksellers_CZ122AA.docx
Saved: Notice_0205_Casey's General Store_CF360X.docx
Saved: Notice_0206_Big Lots_CH648A.docx
Saved: Notice_0207_Hudson's Bay_9T8L0PA.docx
Saved: Notice_0208_Dell Technologies_CE313A.docx
Saved: Notice_0209_Amway_CD975AA.docx
Saved: Notice_0210_Best Buy_7J2M3PA.docx
Saved: Notice_0211_Staples_7S4N7PA.docx
Saved: Notice_0212_Gap_T8W18A.docx
Saved: Notice_0213_Hobby Lobby Stores_81H48PA.docx
Saved: Notice_0214_Discount Tire_3ED51A.docx
Saved: Notice_0215_H.E. Butt Grocery_F9K04A.docx
Saved: Notice_0216_Dell Technologies_44V84PA.docx
Saved: Notice_0217_AT&T Wireless_CZ121AA.docx
Saved: Notice_0218_Sephora (LVMH)_3WX38A.docx
Saved: Notice_0219_Aldi_L0H25A.docx
Saved: Notice_0220_Defense Commissary Agency_3JA81AA.docx
Saved: Notice_0221_O'Reilly Auto Parts_P2V64A.docx
Saved: Notice_0222_Apple Stores _ iTunes_W2303A.docx
Saved: Notice_0223_BJ's Wholesale Club_CF513A.docx
Saved: Notice_0224_My Demoulas_C2P26AA.docx
Saved: Notice_0225_CVS Health Corporation_7Q6Z7PA.docx
Saved: Notice_0226_Sprouts Farmers Market_P2V62A.docx
Saved: Notice_0227_Hudson's Bay_84J08PA.docx
Saved: Notice_0228_Gap_8L145PA.docx
Saved: Notice_0229_Ace Hardware_CF257A.docx
Saved: Notice_0230_Dick's Sporting Goods_A05H9PA.docx
Saved: Notice_0231_Dick's Sporting Goods_7Y6U3PA.docx
Saved: Notice_0232_Health Mart Systems_87G01PA.docx
Saved: Notice_0233_Big Lots_81H48PA.docx
Saved: Notice_0234_Rite Aid_CF231A.docx
Saved: Notice_0235_Sprouts Farmers Market_780A7PA.docx
Saved: Notice_0236_Ace Hardware_7Y6U1PA.docx
Saved: Notice_0237_Nordstrom_7WN44D.docx
Saved: Notice_0238_True Value Co._3WX00A.docx
Saved: Notice_0239_Staples_CZ637AA.docx
Saved: Notice_0240_Ace Hardware_3JA78AA.docx
Saved: Notice_0241_Nordstrom_CF501A.docx
Saved: Notice_0242_AVB Brandsource_7N6V0PA.docx
Saved: Notice_0243_Southeastern Grocers_189T0AA.docx
Saved: Notice_0244_Schnucks_832Q8PA.docx
Saved: Notice_0245_Hy Vee_54R50B.docx
Saved: Notice_0246_Alimentation Couche-Tard_840G6PA.docx
Saved: Notice_0247_Save-A-Lot_8Z7W5PA.docx
Saved: Notice_0248_TJX Companies_P2V69A.docx
Saved: Notice_0249_Big Lots_C4810A.docx
Saved: Notice_0250_Meijer_8L144PA.docx
Saved: Notice_0251_Williams-Sonoma_841W7PA.docx
Saved: Notice_0252_American Eagle_L0S57AA.docx
Saved: Notice_0253_Verizon Wireless_CN056AA.docx
Saved: Notice_0254_Ace Hardware_405W2C.docx
Saved: Notice_0255_Neiman Marcus_W1103A.docx
Saved: Notice_0256_Dell Technologies_9J6K8PA.docx
Saved: Notice_0257_Macy's_8C4R6PA.docx
Saved: Notice_0258_Verizon Wireless_90N54PA.docx
Saved: Notice_0259_WinCo Foods_2Z633A.docx
Saved: Notice_0260_Lululemon_84H53PA.docx
Saved: Notice_0261_Academy Sports_CF256A.docx
Saved: Notice_0262_BJ's Wholesale Club_6L0K9PA.docx
Saved: Notice_0263_Defense Commissary Agency_9E3Q6PA.docx
Saved: Notice_0264_Dillard's_CF214A.docx
Saved: Notice_0265_Ace Hardware_CE321A.docx
Saved: Notice_0266_Casey's General Store_CZ134A.docx
Saved: Notice_0267_Dollar General_CN628AA.docx
Saved: Notice_0268_Giant Eagle_CF350A.docx
Saved: Notice_0269_Dell Technologies_F9K01A.docx
Saved: Notice_0270_Wakefern _ ShopRite_9W6U8PA.docx
Saved: Notice_0271_Hudson's Bay_943S1PA.docx
Saved: Notice_0272_Hobby Lobby Stores_8H9G6PA.docx
Saved: Notice_0273_Total Wine & More_6N030PA.docx
Saved: Notice_0274_Schnucks_F9J77A.docx
Saved: Notice_0275_AutoZone_CF359A.docx
Saved: Notice_0276_Dollar Tree_4K0V9PA.docx
Saved: Notice_0277_CVS Health Corporation_7L033PA.docx
Saved: Notice_0278_AT&T Wireless_4J0N0PA.docx
Saved: Notice_0279_J.C. Penney Company_8L168PA.docx
Saved: Notice_0280_J.C. Penney Company_889G9PA.docx
Saved: Notice_0281_Wayfair_404L7C.docx
Saved: Notice_0282_Staples_W1370A.docx
Saved: Notice_0283_O'Reilly Auto Parts_3WX07A.docx
Saved: Notice_0284_True Value Co._9R291PA.docx
Saved: Notice_0285_Shell Oil Company_CC388A.docx
Saved: Notice_0286_Burlington_CC388X.docx
Saved: Notice_0287_Ingles_7Q6Z7PA.docx
Saved: Notice_0288_Royal Ahold Delhaize USA_8D667PA.docx
Saved: Notice_0289_Ingles_6F967PA.docx
Saved: Notice_0290_Barnes and Noble Booksellers_L0S69AA.docx
Saved: Notice_0291_Sprouts Farmers Market_6ZD29AA.docx
Saved: Notice_0292_Royal Ahold Delhaize USA_6K7U2PA.docx
Saved: Notice_0293_Save-A-Lot_9X5J3PA.docx
Saved: Notice_0294_Walgreens Boots Alliance_72K10PA.docx
Saved: Notice_0295_Dick's Sporting Goods_CC388AD.docx
Saved: Notice_0296_CVS Health Corporation_3WX36A.docx
Saved: Notice_0297_PetSmart_8F8Z0PA.docx
Saved: Notice_0298_Walmart_65P59A6.docx
Saved: Notice_0299_Qurate Retail_CE516A.docx
Saved: Notice_0300_Publix Super Markets_A45Y6PA.docx
Saved: Notice_0301_BJ's Wholesale Club_9T8K8PA.docx
Saved: Notice_0302_Camping World_7Y6U9PA.docx
Saved: Notice_0303_Lowe's Companies_7Y6U2PA.docx
Saved: Notice_0304_Meijer_9R291PA.docx
Saved: Notice_0305_Stater Bros Holdings_C9352AA.docx
Saved: Notice_0306_Kohl's_9U7H2PA.docx
Saved: Notice_0307_Health Mart Systems_CZ123AA.docx
Saved: Notice_0308_Save-A-Lot_L3U43A.docx
Saved: Notice_0309_Albertsons Companies_8AF52A.docx
Saved: Notice_0310_Dillard's_2Z633A.docx
Saved: Notice_0311_Staples_2Z614A.docx
Saved: Notice_0312_O'Reilly Auto Parts_2Z615A.docx
Saved: Notice_0313_Giant Eagle_W2040A.docx
Saved: Notice_0314_PetSmart_7PS84A.docx
Saved: Notice_0315_Lululemon_9Q962PA.docx
Saved: Notice_0316_Wakefern _ ShopRite_8L130PA.docx
Saved: Notice_0317_Dick's Sporting Goods_4J0N0PA.docx
Saved: Notice_0318_Shell Oil Company_3G636A.docx
Saved: Notice_0319_Wegmans Food Market_7W475PA.docx
Saved: Notice_0320_AT&T Wireless_CB542A.docx
Saved: Notice_0321_Tapestry_W1335X.docx
Saved: Notice_0322_Ross Stores_CE285A.docx
Saved: Notice_0323_Petco_6N030PA.docx
Saved: Notice_0324_Nordstrom_9Q9M6PA.docx
Saved: Notice_0325_Ulta Beauty_F9J67A.docx
Saved: Notice_0326_Dick's Sporting Goods_9R4N9PA.docx
Saved: Notice_0327_Dillard's_P2V27A.docx
Saved: Notice_0328_Victoria's Secret_T6M01AA.docx
Saved: Notice_0329_Royal Ahold Delhaize USA_3XB78A.docx
Saved: Notice_0330_AutoZone_C9383A.docx
Saved: Notice_0331_Defense Commissary Agency_2Z632A.docx
Saved: Notice_0332_Gap_W2111X.docx
Saved: Notice_0333_Wayfair_3JA82AA.docx
Saved: Notice_0334_Dillard's_840G6PA.docx
Saved: Notice_0335_Dollar Tree_8F6C5PA.docx
Saved: Notice_0336_Army and Air Force Exchange Service_92Z21PA.docx
Saved: Notice_0337_Lululemon_8U1H3PA.docx
Saved: Notice_0338_Kohl's_9U7H2PA.docx
Saved: Notice_0339_Apple Stores _ iTunes_8L144PA.docx
Saved: Notice_0340_Amazon.com_65P57A6.docx
Saved: Notice_0341_True Value Co._3JA77AA.docx
Saved: Notice_0342_Health Mart Systems_782N0PA.docx
Saved: Notice_0343_Amway_90N54PA.docx
Saved: Notice_0344_My Demoulas_CZ638AA.docx
Saved: Notice_0345_Target_8L149PA.docx
Saved: Notice_0346_Wakefern _ ShopRite_L0S60AA.docx
Saved: Notice_0347_Qurate Retail_C2P04AA.docx
Saved: Notice_0348_Burlington_6X9S0PA.docx
Saved: Notice_0349_Victoria's Secret_6PA50A4.docx
Saved: Notice_0350_Nordstrom_8C4R7PA.docx
Saved: Notice_0351_Williams-Sonoma_40Z26AA.docx
Saved: Notice_0352_Petco_8U6Z2PA.docx
Saved: Notice_0353_Advance Auto_CH562ZZ.docx
Saved: Notice_0354_O'Reilly Auto Parts_CF358A.docx
Saved: Notice_0355_Publix Super Markets_389A1PA.docx
Saved: Notice_0356_Chewy.com_9W6U6PA.docx
Saved: Notice_0357_Target_CH561ZZ.docx
Saved: Notice_0358_Lowe's Companies_843B6PA.docx
Saved: Notice_0359_My Demoulas_CE278A.docx
Saved: Notice_0360_Ikea North American Svcs_498N6A.docx
Saved: Notice_0361_Publix Super Markets_81M38AA.docx
Saved: Notice_0362_Williams-Sonoma_Z7Y69A.docx
Saved: Notice_0363_Raley's Supermarkets_8X059PA.docx
Saved: Notice_0364_The Home Depot_CF362X.docx
Saved: Notice_0365_Tractor Supply Co._C2P23AA.docx
Saved: Notice_0366_The Home Depot_A0EH4PA.docx
Saved: Notice_0367_Kohl's_8L130PA.docx
Saved: Notice_0368_Amway_2Z614A.docx
Saved: Notice_0369_Hudson's Bay_M0H56AA.docx
Saved: Notice_0370_The Home Depot_9Y0Z1PA.docx
Saved: Notice_0371_The Home Depot_6C3G1PA.docx
Saved: Notice_0372_The Home Depot_8F6C9PA.docx
Saved: Notice_0373_Wakefern _ ShopRite_CF402A.docx
Saved: Notice_0374_Amazon.com_7Z481PA.docx
Saved: Notice_0375_True Value Co._7K667PA.docx
Saved: Notice_0376_Menards_X4E79AA.docx
Saved: Notice_0377_Bath & Body Works_Z9M07A.docx
Saved: Notice_0378_Kohl's_8L130PA.docx
Saved: Notice_0379_Rite Aid_6PA50A4.docx
Saved: Notice_0380_O'Reilly Auto Parts_2Z615A.docx
Saved: Notice_0381_Albertsons Companies_9Y0Z1PA.docx
Saved: Notice_0382_7-Eleven_1F3W3A.docx
Saved: Notice_0383_Total Wine & More_F9K06A.docx
Saved: Notice_0384_Lululemon_28C12A.docx
Saved: Notice_0385_Piggly Wiggly_7Y6U1PA.docx
Saved: Notice_0386_Ulta Beauty_3WX06A.docx
Saved: Notice_0387_Neiman Marcus_CZ135A.docx
Saved: Notice_0388_Southeastern Grocers_60K34B.docx
Saved: Notice_0389_Health Mart Systems_F9K02A.docx
Saved: Notice_0390_Signet Jewelers_Z9M05A.docx
Saved: Notice_0391_Schnucks_CZ122AA.docx
Saved: Notice_0392_Signet Jewelers_W1580A.docx
Saved: Notice_0393_Office Depot_1F3Y4A.docx
Saved: Notice_0394_J.C. Penney Company_7G6H1PA.docx
Saved: Notice_0395_Dollar General_8AF45A.docx
Saved: Notice_0396_Nordstrom_9T8K7PA.docx

Letter generation completed.
Total individual letters created: 396
Warning letters: 396
Suspension letters: 0
Output folder: C:\Data Science\MAP Project\MAP Violation letters