# task2 Merge function - merge function used to join 2 dataframes

##  merge() based on columns

In [29]:
import pandas as pd

In [30]:
#two dataframes are created

term1_marks = pd.DataFrame({'names':["Riya","Priya","Raju","Rambo"],
                 'math':[34,34,21,54],
                 'science':[32,54,65,76],
                 'ela':[43,65,76,87],
                 'comp':[33,43,76,87]})
term2_marks = pd.DataFrame({'names':["Riya","Priya","Raju","Rambo"],
                 'math':[54,76,87,98],
                 'science':[54,76,97,59],
                 'ela':[54,85,96,97],
                 'comp':[93,63,96,77]})

#merge function is carried out based on names column and inner merge operation is stated, which is also a default value
# inner merge returns the result dataframe only for the entries present in both the dataframes

result = term1_marks.merge(term2_marks, on = 'names', how = 'inner')

In [31]:
#both the dataframes contain same values on column specified for merge, so all the values are added as extra columns in the result dataframe
result

   names  math_x  science_x  ela_x  comp_x  math_y  science_y  ela_y  comp_y
0   Riya      34         32     43      33      54         54     54      93
1  Priya      34         54     65      43      76         76     85      63
2   Raju      21         65     76      76      87         97     96      96
3  Rambo      54         76     87      87      98         59     97      77

In [32]:
result11 = pd.merge(term1_marks,term2_marks, on = 'names', how = 'outer')
result11

   names  math_x  science_x  ela_x  comp_x  math_y  science_y  ela_y  comp_y
0  Priya      34         54     65      43      76         76     85      63
1   Raju      21         65     76      76      87         97     96      96
2  Rambo      54         76     87      87      98         59     97      77
3   Riya      34         32     43      33      54         54     54      93

In [33]:
#returns all the values in both the dataframes NaN returned for entries not present in other dataframe

result1 = term1_marks.merge(term2_marks, on = 'names', how = 'outer')
result1

   names  math_x  science_x  ela_x  comp_x  math_y  science_y  ela_y  comp_y
0  Priya      34         54     65      43      76         76     85      63
1   Raju      21         65     76      76      87         97     96      96
2  Rambo      54         76     87      87      98         59     97      77
3   Riya      34         32     43      33      54         54     54      93

In [34]:
result22 = pd.merge(term1_marks,term2_marks, on = 'names', how = 'left')
result22

   names  math_x  science_x  ela_x  comp_x  math_y  science_y  ela_y  comp_y
0   Riya      34         32     43      33      54         54     54      93
1  Priya      34         54     65      43      76         76     85      63
2   Raju      21         65     76      76      87         97     96      96
3  Rambo      54         76     87      87      98         59     97      77

In [35]:
result2 = term1_marks.merge(term2_marks, on = 'names', how = 'left')
result2

   names  math_x  science_x  ela_x  comp_x  math_y  science_y  ela_y  comp_y
0   Riya      34         32     43      33      54         54     54      93
1  Priya      34         54     65      43      76         76     85      63
2   Raju      21         65     76      76      87         97     96      96
3  Rambo      54         76     87      87      98         59     97      77

In [36]:
result3 = term1_marks.merge(term2_marks, on = 'names', how = 'right')
result3

   names  math_x  science_x  ela_x  comp_x  math_y  science_y  ela_y  comp_y
0   Riya      34         32     43      33      54         54     54      93
1  Priya      34         54     65      43      76         76     85      63
2   Raju      21         65     76      76      87         97     96      96
3  Rambo      54         76     87      87      98         59     97      77

In [37]:
term1_marks = pd.DataFrame({'names':["Riya","Priya","Raju","Rambo"],
                 'math':[34,34,21,54],
                 'science':[32,54,65,76],
                 'ela':[43,65,76,87],
                 'comp':[33,43,76,87]})
term2_marks = pd.DataFrame({'names':["Riya","Priya","Raju","Rambo","Kavin"],
                 'math':[54,76,87,98,78],
                 'science':[54,76,97,59,90],
                 'ela':[54,85,96,97,96],
                 'comp':[93,63,96,77,89]})
result = term1_marks.merge(term2_marks, on = 'names', how = 'inner')
result

   names  math_x  science_x  ela_x  comp_x  math_y  science_y  ela_y  comp_y
0   Riya      34         32     43      33      54         54     54      93
1  Priya      34         54     65      43      76         76     85      63
2   Raju      21         65     76      76      87         97     96      96
3  Rambo      54         76     87      87      98         59     97      77

In [38]:
#returns all the values in both the dataframes NaN returned for entries not present in other dataframe

result1 = term1_marks.merge(term2_marks, on = 'names', how = 'outer')
result1

   names  math_x  science_x  ela_x  comp_x  math_y  science_y  ela_y  comp_y
0  Kavin     NaN        NaN    NaN     NaN      78         90     96      89
1  Priya    34.0       54.0   65.0    43.0      76         76     85      63
2   Raju    21.0       65.0   76.0    76.0      87         97     96      96
3  Rambo    54.0       76.0   87.0    87.0      98         59     97      77
4   Riya    34.0       32.0   43.0    33.0      54         54     54      93

In [39]:
result2 = term1_marks.merge(term2_marks, on = 'names', how = 'left')
result2

   names  math_x  science_x  ela_x  comp_x  math_y  science_y  ela_y  comp_y
0   Riya      34         32     43      33      54         54     54      93
1  Priya      34         54     65      43      76         76     85      63
2   Raju      21         65     76      76      87         97     96      96
3  Rambo      54         76     87      87      98         59     97      77

In [40]:
### returns the result for the dataframe in right and keeps NaN value if not present in left dataframe

result3 = term1_marks.merge(term2_marks, on = 'names', how = 'right')
result3

   names  math_x  science_x  ela_x  comp_x  math_y  science_y  ela_y  comp_y
0   Riya    34.0       32.0   43.0    33.0      54         54     54      93
1  Priya    34.0       54.0   65.0    43.0      76         76     85      63
2   Raju    21.0       65.0   76.0    76.0      87         97     96      96
3  Rambo    54.0       76.0   87.0    87.0      98         59     97      77
4  Kavin     NaN        NaN    NaN     NaN      78         90     96      89

## row based merging

In [41]:
term1_student_details = pd.DataFrame({'names':["Riya","Priya","Raju","Rambo"],
                 'age':[12,11,12,13],
                 'previous_year':['yes','no','no','yes']})
                 
term1_student_marks = pd.DataFrame({'names':["Riya","Priya","Raju","Rambo","Kavin"],
                 'math':[54,76,87,98,98],
                 'science':[54,76,97,90,97],
                 'ela':[54,96,97,96,97],
                 'comp':[93,96,77,89,99]})

In [42]:
import pandas as pd

In [43]:
result = pd.merge(term1_student_details,term1_student_marks, on='names', how='inner')
result

   names  age previous_year  math  science  ela  comp
0   Riya   12           yes    54       54   54    93
1  Priya   11            no    76       76   96    96
2   Raju   12            no    87       97   97    77
3  Rambo   13           yes    98       90   96    89

In [44]:
result1 = pd.merge(term1_student_details,term1_student_marks, on='names', how='outer')
result1

   names   age previous_year  math  science  ela  comp
0  Kavin   NaN           NaN    98       97   97    99
1  Priya  11.0            no    76       76   96    96
2   Raju  12.0            no    87       97   97    77
3  Rambo  13.0           yes    98       90   96    89
4   Riya  12.0           yes    54       54   54    93

In [45]:
result2 = pd.merge(term1_student_details,term1_student_marks, on='names', how='left')
result2

   names  age previous_year  math  science  ela  comp
0   Riya   12           yes    54       54   54    93
1  Priya   11            no    76       76   96    96
2   Raju   12            no    87       97   97    77
3  Rambo   13           yes    98       90   96    89

In [46]:
result3 = pd.merge(term1_student_details,term1_student_marks, on='names', how='right')
result3

   names   age previous_year  math  science  ela  comp
0   Riya  12.0           yes    54       54   54    93
1  Priya  11.0            no    76       76   96    96
2   Raju  12.0            no    87       97   97    77
3  Rambo  13.0           yes    98       90   96    89
4  Kavin   NaN           NaN    98       97   97    99

## task 3 and 4

### List comprehension - nested loops of series of conditions in a single line

In [47]:
### sum vales calculated for range of numbers corresponding to the length

Internal_marks = [20,19,20,18]
Theory_marks = [76,78,76,79]

Total_marks =[[Internal_marks[i] + Theory_marks[i] for i in range(len(Internal_marks))]]

Total_marks

[[96, 97, 96, 97]]

#### same as above executed using map() in lambda

In [48]:
## using map() in lambda

Internal_marks = [20,19,20,18]
Theory_marks = [76,78,76,79]

Total_marks = list(map(lambda x, y: x + y, Internal_marks, Theory_marks))

Total_marks

[96, 97, 96, 97]

In [49]:
## create a list of grade_2 level salary from the given mixed list of salary

salary = [18000, 20000, 30000, 34000, 50000]
grade_2_salary = [a for a in salary if a >= 25000]
grade_2_salary

[30000, 34000, 50000]

#### same as above executed using filter in lambda

In [50]:
salary = [48000, 20000, 30000, 34000, 50000,21000]
grade_2_salary = list(filter(lambda a: a >= 25000, salary))
grade_2_salary

[48000, 30000, 34000, 50000]

### reduce in lambda

In [51]:
from functools import reduce

no_of_orders = [21,43,76,98,87,54]
total_orders = reduce(lambda x, y: x + y, no_of_orders)
total_orders

379

In [52]:
from functools import reduce

gross_amount = [21432,43546,7326,98768,8327,56574]
total_amount = reduce(lambda x, y: x + y, gross_amount)
total_amount

235973